timezone: "America/Sao_Paulo"
rodada_id: "2025-09-20_21"

provider:
  name: "api_football"
  base_url: "https://api-football-v1.p.rapidapi.com/v3"
  # Ligas foco (ajuste conforme seu alvo/ID do seu plano)
  league_br: "71"    # Brasileirão Série A
  league_lib: "13"   # Libertadores
  league_epl: "39"   # Premier League
  season: "2025"

# >>> NÃO use referência por string tipo ${headers_rapidapi} <<<
# Em vez disso, escreva o MAPA de headers diretamente em cada seção:
#   X-RapidAPI-Key usa ${TOKEN} e o script substitui pelo valor do secret RAPIDAPI_KEY.

fixtures_odds:
  api_url_fixtures: "${base_url}/fixtures"
  api_url_odds:     "${base_url}/odds"
  api_token_env: "RAPIDAPI_KEY"
  api_headers:
    X-RapidAPI-Key: "${TOKEN}"
    X-RapidAPI-Host: "api-football-v1.p.rapidapi.com"
  params_fixtures:
    league: "${league_br}"   # troque para ${league_lib} ou ${league_epl} quando quiser
    season: "${season}"
    round: "${rodada}"       # script converte para "Regular Season - NN" automaticamente
  params_odds:
    league: "${league_br}"
    season: "${season}"

standings:
  mode: "api"
  api_url: "${base_url}/standings"
  api_token_env: "RAPIDAPI_KEY"
  api_headers:
    X-RapidAPI-Key: "${TOKEN}"
    X-RapidAPI-Host: "api-football-v1.p.rapidapi.com"
  api_params:
    league: "${league_br}"
    season: "${season}"

availability:
  api_token_env: "RAPIDAPI_KEY"
  api_headers:
    X-RapidAPI-Key: "${TOKEN}"
    X-RapidAPI-Host: "api-football-v1.p.rapidapi.com"
  endpoints:
    lineups:   "${base_url}/fixtures/lineups"   # ?fixture=<id>
    injuries:  "${base_url}/injuries"           # ?fixture=<id>

weather:
  hourly: ["temperature_2m", "precipitation_probability", "precipitation", "wind_speed_10m"]
  forecast_days: 5
  past_days: 0

sanity:
  min_bookmakers: 3
  max_vig: 0.12
  max_prob_shift: 0.20

paths:
  matches_csv: "data/raw/rodada_${rodada}/matches.csv"
  stadiums_csv: "data/raw/stadiums_latlon.csv"
  fixtures_out: "data/processed/fixtures_${rodada}.csv"
  odds_out: "data/processed/odds_${rodada}.csv"
  standings_out: "data/processed/standings_${rodada}.csv"
  availability_out: "data/processed/availability_${rodada}.csv"
  weather_out: "data/processed/weather_${rodada}.csv"
  joined_out: "data/processed/joined_${rodada}.csv"
  context_score_out: "reports/context_scores_${rodada}.csv"
