name: End2End - Odds → Consenso → Predição → Cartão

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  end2end:
    runs-on: ubuntu-latest
    env:
      SEASON: '2025'
      REGIONS: 'uk,eu,us,au'
      BANKROLL: '1000'
      KELLY_FRACTION: '0.5'
      KELLY_CAP: '0.1'
      ROUND_TO: '1'
      KELLY_TOP_N: '14'
      DEBUG: 'true'
      # Ajuste aqui os sports do TheOddsAPI conforme os jogos do dia:
      # Ex.: Argentina
      ODDS_SPORTS: 'soccer_argentina_primera_division,soccer_argentina_primera_nacional'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Define RODADA_ID / OUT_DIR
        run: |
          set -e
          echo "RODADA_ID=${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo "OUT_DIR=data/out/${GITHUB_RUN_ID}" >> $GITHUB_ENV
          mkdir -p "data/in" "${GITHUB_WORKSPACE}/data/out/${GITHUB_RUN_ID}"

      - name: Sanity - matches_source.csv existe
        run: |
          set -e
          if [ ! -f "data/in/matches_source.csv" ]; then
            echo "::error::data/in/matches_source.csv não encontrado."
            echo "Formato mínimo: match_key,home,away"
            exit 2
          fi
          echo "OK: data/in/matches_source.csv"

      - name: Coletar odds (TheOddsAPI)
        env:
          THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
        run: |
          set -e
          if [ -z "${THEODDS_API_KEY}" ]; then
            echo "::warning::THEODDS_API_KEY ausente — pulando coleta."
            # ainda criamos arquivos vazios com cabeçalho para não quebrar
            mkdir -p "${OUT_DIR}"
            printf "match_key,team_home,team_away,odds_home,odds_draw,odds_away\n" > "${OUT_DIR}/odds_theoddsapi.csv"
            printf "match_key,home,away,reason\n" > "${OUT_DIR}/unmatched_theoddsapi.csv"
          else
            python scripts/ingest_odds_theoddsapi_safe.py \
              --rodada "${OUT_DIR}" \
              --regions "${REGIONS}" \
              --sports "${ODDS_SPORTS}" \
              --debug
          fi
          ls -la "${OUT_DIR}" || true

      - name: Consolidar odds (consensus)
        run: |
          set -e
          python -m scripts.consensus_odds_safe --rodada "${RODADA_ID}"
          echo "==== odds_consensus.csv ===="
          head -n 30 "data/out/${RODADA_ID}/odds_consensus.csv" || true
          echo "==========================="

      - name: Predizer resultados (market)
        run: |
          set -e
          python scripts/predict_from_odds.py --rodada "${RODADA_ID}" --debug || true
          echo "==== predictions_market.csv ===="
          head -n 30 "data/out/${RODADA_ID}/predictions_market.csv" || true
          echo "==============================="

      - name: Gerar cartão da Loteca
        run: |
          set -e
          python scripts/build_cartao.py --rodada "${RODADA_ID}" || true
          echo "==== loteca_cartao.txt ===="
          cat "data/out/${RODADA_ID}/loteca_cartao.txt" || true

      - name: Publicar Kelly (opcional)
        run: |
          set -e
          if [ -f "scripts/publish_kelly.py" ]; then
            python scripts/publish_kelly.py --rodada "${RODADA_ID}" --debug || true
          else
            echo "::warning::publish_kelly.py não encontrado."
          fi

      - name: Upload artefatos
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ env.RODADA_ID }}
          path: |
            data/out/${{ env.RODADA_ID }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/odds_apifootball.csv
            data/out/${{ env.RODADA_ID }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA_ID }}/odds_consensus.csv
            data/out/${{ env.RODADA_ID }}/predictions_market.csv
            data/out/${{ env.RODADA_ID }}/news.csv
            data/out/${{ env.RODADA_ID }}/injuries.csv
            data/out/${{ env.RODADA_ID }}/loteca_cartao.txt
            data/out/${{ env.RODADA_ID }}/kelly_stakes.csv
          if-no-files-found: warn