name: end2end-odds-news-ml

on:
  workflow_dispatch:
    inputs:
      RODADA:
        description: "Identificador da rodada (ex: 2025-09-27_1213)"
        required: true
        default: "2025-09-27_1213"
      SEASON:
        description: "Temporada (ex: 2025)"
        required: true
        default: "2025"
      REGIONS:
        description: "Regiões TheOddsAPI (ex: uk,eu,us,au)"
        required: true
        default: "uk,eu,us,au"
      BANKROLL:
        description: "Bankroll inicial"
        required: true
        default: "1000"
      KELLY_FRACTION:
        description: "Fração de Kelly"
        required: true
        default: "0.5"
      KELLY_CAP:
        description: "Cap de Kelly por aposta"
        required: true
        default: "0.1"
      MIN_STAKE:
        description: "Stake mínima"
        required: true
        default: "0"
      MAX_STAKE:
        description: "Stake máxima (0 = sem limite)"
        required: true
        default: "0"
      ROUND_TO:
        description: "Arredondar stake para múltiplos de"
        required: true
        default: "1"
      KELLY_TOP_N:
        description: "Número máximo de jogos no Kelly"
        required: true
        default: "14"

env:
  # inputs
  RODADA: ${{ github.event.inputs.RODADA }}
  SEASON: ${{ github.event.inputs.SEASON }}
  REGIONS: ${{ github.event.inputs.REGIONS }}
  BANKROLL: ${{ github.event.inputs.BANKROLL }}
  KELLY_FRACTION: ${{ github.event.inputs.KELLY_FRACTION }}
  KELLY_CAP: ${{ github.event.inputs.KELLY_CAP }}
  MIN_STAKE: ${{ github.event.inputs.MIN_STAKE }}
  MAX_STAKE: ${{ github.event.inputs.MAX_STAKE }}
  ROUND_TO: ${{ github.event.inputs.ROUND_TO }}
  KELLY_TOP_N: ${{ github.event.inputs.KELLY_TOP_N }}

  # debug fixo (tirei do inputs para respeitar o limite de 10)
  DEBUG: "true"

  # secrets/vars
  THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
  X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
  NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
  WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
  APIFOOT_LEAGUE_ID: ${{ secrets.APIFOOT_LEAGUE_ID }}

jobs:
  end2end:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Expose PYTHONPATH
        shell: bash
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Verificar entrada (matches_source.csv)
        shell: bash
        run: |
          set -e
          if [ ! -f "data/in/${RODADA}/matches_source.csv" ]; then
            echo "ERRO: data/in/${RODADA}/matches_source.csv não encontrado"
            exit 2
          fi
          echo "Entrada OK: data/in/${RODADA}/matches_source.csv"

      - name: Checar chaves de API
        shell: bash
        run: |
          set -e
          [ -z "${THEODDS_API_KEY}" ] && echo "AVISO: THEODDS_API_KEY ausente (TheOddsAPI será pulado)." || echo "THEODDS_API_KEY: OK"
          [ -z "${X_RAPIDAPI_KEY}" ] && echo "AVISO: X_RAPIDAPI_KEY ausente (API-Football será pulado)." || echo "X_RAPIDAPI_KEY: OK"
          [ -z "${NEWSAPI_KEY}" ] && echo "AVISO: NEWSAPI_KEY ausente (News será pulado)." || echo "NEWSAPI_KEY: OK"

      - name: (Opcional) Login Weights & Biases
        shell: bash
        run: |
          set -e
          if [ -n "${WANDB_API_KEY}" ]; then
            python -m wandb login "${WANDB_API_KEY}" --relogin || true
            echo "[wandb] login executado"
          else
            echo "[wandb] AVISO: WANDB_API_KEY ausente — seguindo sem W&B."
          fi

      # ===== Ingestão de odds =====
      - name: Ingest TheOddsAPI (safe)
        if: env.THEODDS_API_KEY != ''
        shell: bash
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/ingest_odds_theoddsapi_safe.py" ]; then
            python scripts/ingest_odds_theoddsapi_safe.py \
              --rodada "${RODADA}" \
              --regions "${REGIONS}" \
              ${EXTRA}
          else
            echo "[theoddsapi-safe] AVISO: scripts/ingest_odds_theoddsapi_safe.py não encontrado — pulando."
          fi

      - name: Ingest API-Football via RapidAPI (safe + fallback)
        if: env.X_RAPIDAPI_KEY != ''
        shell: bash
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/ingest_odds_apifootball_rapidapi_safe.py" ]; then
            python scripts/ingest_odds_apifootball_rapidapi_safe.py \
              --rodada "${RODADA}" \
              --season "${SEASON}" \
              ${EXTRA} || true
          elif [ -f "scripts/ingest_odds_apifootball_rapidapi.py" ]; then
            python -m scripts.ingest_odds_apifootball_rapidapi \
              --rodada "${RODADA}" \
              --season "${SEASON}" \
              --window 2 \
              --fuzzy 0.90 \
              --aliases data/aliases_br.json \
              ${EXTRA} || true
          else
            echo "[apifootball-safe] AVISO: script de ingestão não encontrado — pulando."
          fi

      # ===== Consenso (ACEITA 1 PROVEDOR) =====
      - name: Consensus (safe)
        shell: bash
        run: |
          set -e
          if python -c "import importlib.util; import sys; sys.exit(0 if importlib.util.find_spec('scripts.consensus_odds_safe') else 1)"; then
            python -m scripts.consensus_odds_safe --rodada "${RODADA}"
          else
            echo "[consensus-safe] ERRO: módulo scripts.consensus_odds_safe não encontrado."
            exit 10
          fi

      # ===== Previsões a partir das odds do mercado =====
      - name: Predict from odds (market)
        shell: bash
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/predict_from_odds.py" ]; then
            python scripts/predict_from_odds.py --rodada "${RODADA}" ${EXTRA}
          else
            echo "[predict] ERRO: scripts/predict_from_odds.py não encontrado."
            exit 11
          fi

      # ===== News & Injuries (opcional) =====
      - name: Ingest News (opcional)
        if: env.NEWSAPI_KEY != ''
        shell: bash
        run: |
          set -e
          if [ -f "scripts/news_ingest_safe.py" ]; then
            python scripts/news_ingest_safe.py
          else
            echo "[news-safe] AVISO: scripts/news_ingest_safe.py não encontrado — pulando news."
          fi

      - name: Injuries (opcional, via API-Football)
        if: env.X_RAPIDAPI_KEY != ''
        shell: bash
        run: |
          set -e
          if [ -f "scripts/injuries_apifootball_safe.py" ]; then
            python scripts/injuries_apifootball_safe.py
          else
            echo "[injuries-safe] AVISO: scripts/injuries_apifootball_safe.py não encontrado — pulando injuries."
          fi

      # ===== Cartão da Loteca e Kelly =====
      - name: Build Cartão da Loteca (14 jogos)
        shell: bash
        run: |
          set -e
          if [ -f "scripts/build_cartao.py" ]; then
            python scripts/build_cartao.py --rodada "${RODADA}"
          else
            echo "[cartao] ERRO: scripts/build_cartao.py não encontrado."
            exit 12
          fi

      - name: Kelly Stakes
        shell: bash
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/publish_kelly.py" ]; then
            python scripts/publish_kelly.py --rodada "${RODADA}" ${EXTRA}
          else
            echo "[kelly] AVISO: scripts/publish_kelly.py não encontrado — pulando Kelly."
          fi

      # ===== Artefatos =====
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ env.RODADA }}
          path: |
            data/out/${{ env.RODADA }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA }}/odds_apifootball.csv
            data/out/${{ env.RODADA }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA }}/odds_consensus.csv
            data/out/${{ env.RODADA }}/predictions_market.csv
            data/out/${{ env.RODADA }}/news.csv
            data/out/${{ env.RODADA }}/injuries.csv
            data/out/${{ env.RODADA }}/loteca_cartao.txt
            data/out/${{ env.RODADA }}/predictions_xg_uni.csv
            data/out/${{ env.RODADA }}/predictions_xg_bi.csv
            data/out/${{ env.RODADA }}/predictions_calibrated.csv
            data/out/${{ env.RODADA }}/predictions_stacked.csv
            data/out/${{ env.RODADA }}/kelly_stakes.csv
            data/out/${{ env.RODADA }}/debug/**
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
