name: end2end-odds-news-ml

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Rodada (ex: 2025-09-27_1213)"
        required: true
        default: "2025-09-27_1213"
      season:
        description: "Temporada (ex: 2025)"
        required: true
        default: "2025"
      regions:
        description: "Regiões TheOddsAPI"
        required: true
        default: "uk,eu,us,au"
      bankroll:
        description: "Bankroll inicial"
        required: true
        default: "1000"
      kelly_fraction:
        description: "Fração de Kelly"
        required: true
        default: "0.5"
      kelly_cap:
        description: "Teto Kelly por aposta"
        required: true
        default: "0.1"
      kelly_top_n:
        description: "Máx. picks publicados"
        required: true
        default: "14"
      apifoot_league_ids:
        description: "League IDs API-Football (CSV) — ex: 71,72"
        required: false
        default: "71,72"

jobs:
  end2end:
    runs-on: ubuntu-24.04
    env:
      DEBUG: "true"
      RODADA: ${{ github.event.inputs.rodada }}
      SEASON: ${{ github.event.inputs.season }}
      REGIONS: ${{ github.event.inputs.regions }}
      BANKROLL: ${{ github.event.inputs.bankroll }}
      KELLY_FRACTION: ${{ github.event.inputs.kelly_fraction }}
      KELLY_CAP: ${{ github.event.inputs.kelly_cap }}
      KELLY_TOP_N: ${{ github.event.inputs.kelly_top_n }}
      APIFOOT_LEAGUE_IDS: ${{ github.event.inputs.apifoot_league_ids }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Sanity check de entrada
        run: |
          set -e
          if [ ! -f "data/in/${RODADA}/matches_source.csv" ]; then
            echo "ERRO: data/in/${RODADA}/matches_source.csv não encontrado"
            exit 2
          fi
          echo "Entrada OK: data/in/${RODADA}/matches_source.csv"

      - name: Checar secrets presentes
        env:
          THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
          X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          set -e
          [ -z "${THEODDS_API_KEY}" ] && echo "AVISO: THEODDS_API_KEY ausente (TheOddsAPI será pulado)." || echo "THEODDS_API_KEY: OK"
          [ -z "${X_RAPIDAPI_KEY}" ] && echo "AVISO: X_RAPIDAPI_KEY ausente (API-Football será pulado)." || echo "X_RAPIDAPI_KEY: OK"
          [ -z "${NEWSAPI_KEY}" ] && echo "AVISO: NEWSAPI_KEY ausente (News será pulado)." || echo "NEWSAPI_KEY: OK"

      - name: W&B login (opcional)
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          set -e
          if [ -n "${WANDB_API_KEY}" ]; then
            python -m wandb login "${WANDB_API_KEY}" --relogin || true
            echo "[wandb] login executado"
          else
            echo "[wandb] AVISO: WANDB_API_KEY ausente — seguindo sem W&B."
          fi

      - name: Ingest TheOddsAPI (safe)
        if: ${{ env.THEODDS_API_KEY != '' }}
        env:
          THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
        run: |
          set -e
          if [ -f "scripts/ingest_odds_theoddsapi_safe.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/ingest_odds_theoddsapi_safe.py --rodada "${RODADA}" --regions "${REGIONS}" ${EXTRA}
          else
            echo "[theoddsapi-safe] AVISO: scripts/ingest_odds_theoddsapi_safe.py não encontrado — pulando."
          fi

      - name: Ingest API-Football (odds) via RapidAPI (safe)
        if: ${{ env.X_RAPIDAPI_KEY != '' }}
        env:
          X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/ingest_odds_apifootball_rapidapi_safe.py" ]; then
            python scripts/ingest_odds_apifootball_rapidapi_safe.py \
              --rodada "${RODADA}" \
              --season "${SEASON}" \
              --leagues "${APIFOOT_LEAGUE_IDS}" \
              --window 2 \
              --fuzzy 0.90 \
              --aliases data/aliases_br.json \
              ${EXTRA} || true
          else
            echo "[apifootball-safe] AVISO: script de ingestão não encontrado — pulando."
          fi

      - name: Consenso de odds (safe)
        run: |
          set -e
          if python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('scripts.consensus_odds_safe') else 1)"; then
            python -m scripts.consensus_odds_safe --rodada "${RODADA}"
          else
            echo "[consensus-safe] AVISO: módulo scripts.consensus_odds_safe não encontrado — pulando."
          fi

      - name: News ingest (opcional)
        if: ${{ env.NEWSAPI_KEY != '' }}
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          set -e
          if [ -f "scripts/news_ingest_safe.py" ]; then
            python scripts/news_ingest_safe.py
          else
            echo "[news-safe] AVISO: scripts/news_ingest_safe.py não encontrado — pulando news."
          fi

      - name: Injuries (API-Football) (opcional)
        if: ${{ env.X_RAPIDAPI_KEY != '' }}
        env:
          X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
        run: |
          set -e
          if [ -f "scripts/injuries_apifootball_safe.py" ]; then
            python scripts/injuries_apifootball_safe.py
          else
            echo "[injuries-safe] AVISO: scripts/injuries_apifootball_safe.py não encontrado — pulando injuries."
          fi

      - name: Predict from odds (sem ML, fallback)
        run: |
          set -e
          if [ -f "scripts/predict_from_odds.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/predict_from_odds.py --rodada "${RODADA}" ${EXTRA} || true
          else
            echo "[predict] AVISO: scripts/predict_from_odds.py não encontrado — pulando predict."
          fi

      - name: Publicar Kelly
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          if [ -f "scripts/publish_kelly.py" ]; then
            python scripts/publish_kelly.py --rodada "${RODADA}" ${EXTRA}
          else
            echo "[kelly] AVISO: scripts/publish_kelly.py não encontrado — pulando Kelly."
          fi

      - name: Build cartão
        run: |
          set -e
          if [ -f "scripts/build_cartao.py" ]; then
            python scripts/build_cartao.py
          else
            echo "[cartao] AVISO: scripts/build_cartao.py não encontrado — pulando cartão."
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ env.RODADA }}
          path: |
            data/out/${{ env.RODADA }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA }}/odds_apifootball.csv
            data/out/${{ env.RODADA }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA }}/odds_consensus.csv
            data/out/${{ env.RODADA }}/news.csv
            data/out/${{ env.RODADA }}/injuries.csv
            data/out/${{ env.RODADA }}/loteca_cartao.txt
            data/out/${{ env.RODADA }}/predictions_from_odds.csv
            data/out/${{ env.RODADA }}/kelly_stakes.csv
            data/out/${{ env.RODADA }}/debug/**
          if-no-files-found: warn
