name: End2End • Odds + News + ML

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-10-04_1214)"
        type: string
        required: true
      season:
        description: "Temporada (ex.: 2025)"
        type: string
        required: true
        default: "2025"
      regions:
        description: "Regiões do TheOddsAPI (uk,eu,us,au)"
        type: string
        required: true
        default: "uk,eu,us,au"
      bankroll:
        description: "Bankroll inicial (para Kelly)"
        type: number
        required: true
        default: 1000
      kelly_fraction:
        description: "Fração de Kelly"
        type: number
        required: true
        default: 0.5
      kelly_cap:
        description: "Teto de Kelly por aposta"
        type: number
        required: true
        default: 0.1
      round_to:
        description: "Arredondamento de stake (ex.: 1)"
        type: number
        required: true
        default: 1
      kelly_top_n:
        description: "Quantidade de picks (Top N)"
        type: number
        required: true
        default: 14
      apifoot_league_ids:
        description: "IDs de ligas da API-Football (ex.: 71,72). Pode ficar vazio."
        type: string
        required: false
        default: ""
      debug:
        description: "Modo debug (true/false)"
        type: boolean
        required: true
        default: true

jobs:
  end2end:
    runs-on: ubuntu-24.04
    env:
      # Inputs
      RODADA: ${{ inputs.rodada }}
      SEASON: ${{ inputs.season }}
      REGIONS: ${{ inputs.regions }}
      BANKROLL: ${{ inputs.bankroll }}
      KELLY_FRACTION: ${{ inputs.kelly_fraction }}
      KELLY_CAP: ${{ inputs.kelly_cap }}
      ROUND_TO: ${{ inputs.round_to }}
      KELLY_TOP_N: ${{ inputs.kelly_top_n }}
      APIFOOT_LEAGUE_IDS: ${{ inputs.apifoot_league_ids }}
      DEBUG: ${{ inputs.debug }}

      # Secrets
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export PYTHONPATH
        shell: bash
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      # ──────────────────────────────────────────────
      # Debug para confirmar presença do arquivo de entrada
      - name: Debug input presence
        shell: bash
        run: |
          set -e
          echo "RODADA=${RODADA}"
          FILE="data/in/${RODADA}/matches_source.csv"
          if [ -f "$FILE" ]; then
            echo "[OK] Encontrado: $FILE"
            head -n 20 "$FILE"
          else
            echo "[ERRO] Não encontrado: $FILE"
          fi

      - name: Validate matches_source.csv presence
        shell: bash
        run: |
          set -e
          FILE="data/in/${RODADA}/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            echo "::error::Arquivo $FILE não encontrado."
            exit 2
          fi
          echo "Entrada OK: $FILE"

      - name: Verify matches_source.csv schema
        shell: bash
        run: |
          python scripts/verify_matches_input.py --rodada "${RODADA}"

      - name: Weights & Biases login (opcional)
        if: env.WANDB_API_KEY != ''
        shell: bash
        run: |
          python -m wandb login "${WANDB_API_KEY}" --relogin || true

      # ──────────────────────────────────────────────
      # Ingestão Odds - TheOddsAPI
      - name: Ingest • TheOddsAPI
        shell: bash
        run: |
          set -e
          if [ -z "${THEODDS_API_KEY}" ]; then
            echo "[theoddsapi] SKIP"
            exit 0
          fi
          python scripts/ingest_odds_theoddsapi_safe.py \
            --rodada "${RODADA}" \
            --regions "${REGIONS}" \
            $([ "${DEBUG}" = "true" ] && echo "--debug")

      # Ingestão Odds - API-Football (opcional)
      - name: Ingest • API-Football
        shell: bash
        run: |
          set -e
          if [ -z "${X_RAPIDAPI_KEY}" ] || [ -z "${APIFOOT_LEAGUE_IDS}" ]; then
            echo "[apifootball] SKIP"
            exit 0
          fi
          python scripts/ingest_odds_apifootball_rapidapi_safe.py \
            --rodada "${RODADA}" \
            --season "${SEASON}" \
            --league-ids "${APIFOOT_LEAGUE_IDS}" \
            $([ "${DEBUG}" = "true" ] && echo "--debug")

      # Consenso de Odds
      - name: Consensus Odds
        shell: bash
        run: |
          python -m scripts.consensus_odds_safe --rodada "${RODADA}"

      # Predições
      - name: Predict from Odds
        shell: bash
        run: |
          python scripts/predict_from_odds.py --rodada "${RODADA}" \
            $([ "${DEBUG}" = "true" ] && echo "--debug")

      # Notícias
      - name: News ingest
        shell: bash
        run: |
          if [ -z "${NEWSAPI_KEY}" ]; then
            echo "[news] SKIP"
            exit 0
          fi
          python scripts/news_ingest_safe.py

      # Lesões
      - name: Injuries ingest
        shell: bash
        run: |
          if [ -z "${X_RAPIDAPI_KEY}" ]; then
            echo "[injuries] SKIP"
            exit 0
          fi
          python scripts/injuries_apifootball_safe.py

      # Cartão
      - name: Build Cartão
        shell: bash
        run: |
          python scripts/build_cartao.py --rodada "${RODADA}"

      # Kelly
      - name: Publish Kelly
        shell: bash
        run: |
          python scripts/publish_kelly.py --rodada "${RODADA}" \
            $([ "${DEBUG}" = "true" ] && echo "--debug")

      # Reality Check
      - name: Reality Check
        continue-on-error: true
        shell: bash
        run: |
          python scripts/sanity_reality_check.py --rodada "${RODADA}" --strict || true

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ inputs.rodada }}
          path: |
            data/out/${{ inputs.rodada }}/**
          if-no-files-found: warn
          compression-level: 6