name: end2end

on:
  workflow_dispatch:
    inputs:
      RODADA:
        description: 'ID da rodada (ex: 2025-10-04_1214)'
        required: true
        default: '2025-10-04_1214'
      SEASON:
        description: 'Temporada (ex: 2025)'
        required: true
        default: '2025'
      REGIONS:
        description: 'Regiões do TheOddsAPI (uk,eu,us,au)'
        required: true
        default: 'uk,eu,us,au'
      BANKROLL:
        description: 'Bankroll inicial'
        required: true
        default: '1000'
      KELLY_FRACTION:
        description: 'Fração Kelly'
        required: true
        default: '0.5'
      KELLY_CAP:
        description: 'Cap Kelly'
        required: true
        default: '0.1'
      ROUND_TO:
        description: 'Arredondar stake para'
        required: true
        default: '1'
      KELLY_TOP_N:
        description: 'Quantidade máxima de picks'
        required: true
        default: '14'
      DEBUG:
        description: 'Debug (true/false)'
        required: true
        default: 'true'
      APIFOOT_LEAGUE_IDS:
        description: 'IDs da API-Football separados por vírgula (ex: 71,72)'
        required: false
        default: '71,72'

jobs:
  end2end:
    runs-on: ubuntu-24.04

    env:
      RODADA: ${{ inputs.RODADA }}
      SEASON: ${{ inputs.SEASON }}
      REGIONS: ${{ inputs.REGIONS }}
      BANKROLL: ${{ inputs.BANKROLL }}
      KELLY_FRACTION: ${{ inputs.KELLY_FRACTION }}
      KELLY_CAP: ${{ inputs.KELLY_CAP }}
      ROUND_TO: ${{ inputs.ROUND_TO }}
      KELLY_TOP_N: ${{ inputs.KELLY_TOP_N }}
      DEBUG: ${{ inputs.DEBUG }}
      APIFOOT_LEAGUE_IDS: ${{ inputs.APIFOOT_LEAGUE_IDS }}
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Expose PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Conferir entrada
        run: |
          set -e
          if [ ! -f "data/in/${RODADA}/matches_source.csv" ]; then
            echo "ERRO: data/in/${RODADA}/matches_source.csv não encontrado"
            exit 2
          fi
          echo "Entrada OK: data/in/${RODADA}/matches_source.csv"

      - name: Chaves presentes?
        run: |
          set -e
          [ -z "${THEODDS_API_KEY}" ] && echo "AVISO: THEODDS_API_KEY ausente (TheOddsAPI será pulado)." || echo "THEODDS_API_KEY: OK"
          [ -z "${X_RAPIDAPI_KEY}" ] && echo "AVISO: X_RAPIDAPI_KEY ausente (API-Football será pulado)." || echo "X_RAPIDAPI_KEY: OK"
          [ -z "${NEWSAPI_KEY}" ] && echo "AVISO: NEWSAPI_KEY ausente (News será pulado)." || echo "NEWSAPI_KEY: OK"

      - name: Weights & Biases login (opcional)
        if: env.WANDB_API_KEY != ''
        run: |
          set -e
          python -m wandb login "${WANDB_API_KEY}" --relogin || true
          echo "[wandb] login executado"

      # ---------------- Ingestão de odds ----------------
      - name: TheOddsAPI (safe)
        if: env.THEODDS_API_KEY != ''
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          python scripts/ingest_odds_theoddsapi_safe.py \
            --rodada "${RODADA}" \
            --regions "${REGIONS}" \
            ${EXTRA}

      - name: API-Football (safe)
        if: env.X_RAPIDAPI_KEY != '' && env.APIFOOT_LEAGUE_IDS != ''
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          python -m scripts.ingest_odds_apifootball_rapidapi \
            --rodada "${RODADA}" \
            --season "${SEASON}" \
            --window 2 \
            --fuzzy 0.90 \
            --aliases data/aliases_br.json \
            ${EXTRA}

      - name: Consenso de odds (tolerante a 1 provedor)
        run: |
          set -e
          if python -c "import importlib.util,sys;sys.exit(0 if importlib.util.find_spec('scripts.consensus_odds_safe') else 1)"; then
            python -m scripts.consensus_odds_safe --rodada "${RODADA}"
          else
            echo "[consensus-safe] ERRO: módulo scripts.consensus_odds_safe não encontrado."
            exit 10
          fi

      # ---------------- Predição via mercado ----------------
      - name: Predição (market-implied)
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          python scripts/predict_from_odds.py --rodada "${RODADA}" ${EXTRA}

      # ---------------- News & Injuries ----------------
      - name: News (opcional)
        if: env.NEWSAPI_KEY != ''
        run: |
          set -e
          python scripts/news_ingest_safe.py

      - name: Injuries via API-Football (opcional)
        if: env.X_RAPIDAPI_KEY != '' && env.APIFOOT_LEAGUE_IDS != ''
        run: |
          set -e
          python scripts/injuries_apifootball_safe.py

      # ---------------- ML (uni, bi, calibração, stacking) ----------------
      - name: XG univariado (opcional)
        run: |
          set -e
          if [ -f "scripts/ml_xg_univariado.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/ml_xg_univariado.py --rodada "${RODADA}" --season "${SEASON}" ${EXTRA} || true
          else
            echo "[ml] AVISO: scripts/ml_xg_univariado.py não encontrado — pulando."
          fi

      - name: XG bivariado (opcional)
        run: |
          set -e
          if [ -f "scripts/ml_xg_bivariado.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/ml_xg_bivariado.py --rodada "${RODADA}" --season "${SEASON}" ${EXTRA} || true
          else
            echo "[ml] AVISO: scripts/ml_xg_bivariado.py não encontrado — pulando."
          fi

      - name: Calibração isotônica (opcional)
        run: |
          set -e
          if [ -f "scripts/ml_calibracao_isotonica.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/ml_calibracao_isotonica.py --rodada "${RODADA}" --season "${SEASON}" ${EXTRA} || true
          else
            echo "[ml] AVISO: scripts/ml_calibracao_isotonica.py não encontrado — pulando."
          fi

      - name: Stacking bivariado (opcional)
        run: |
          set -e
          if [ -f "scripts/ml_stacking_bivariado.py" ]; then
            EXTRA=""
            [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
            python scripts/ml_stacking_bivariado.py --rodada "${RODADA}" --season "${SEASON}" ${EXTRA} || true
          else
            echo "[ml] AVISO: scripts/ml_stacking_bivariado.py não encontrado — pulando."
          fi

      # ---------------- Cartão Loteca & Kelly ----------------
      - name: Cartão Loteca (sempre passar --rodada)
        run: |
          set -e
          python scripts/build_cartao.py --rodada "${RODADA}"

      - name: Publicar Kelly
        run: |
          set -e
          EXTRA=""
          [ "${DEBUG}" = "true" ] && EXTRA="--debug" || true
          python scripts/publish_kelly.py --rodada "${RODADA}" ${EXTRA}

      # ---------------- Sanity & reality check ----------------
      - name: Sanity reality check
        run: |
          set -e
          python scripts/sanity_reality_check.py --rodada "${RODADA}" --strict || true

      # ---------------- Artefatos ----------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ inputs.RODADA }}
          path: |
            data/out/${{ inputs.RODADA }}/odds_theoddsapi.csv
            data/out/${{ inputs.RODADA }}/unmatched_theoddsapi.csv
            data/out/${{ inputs.RODADA }}/odds_apifootball.csv
            data/out/${{ inputs.RODADA }}/unmatched_apifootball.csv
            data/out/${{ inputs.RODADA }}/odds_consensus.csv
            data/out/${{ inputs.RODADA }}/predictions_market.csv
            data/out/${{ inputs.RODADA }}/news.csv
            data/out/${{ inputs.RODADA }}/injuries.csv
            data/out/${{ inputs.RODADA }}/predictions_xg_uni.csv
            data/out/${{ inputs.RODADA }}/predictions_xg_bi.csv
            data/out/${{ inputs.RODADA }}/predictions_calibrated.csv
            data/out/${{ inputs.RODADA }}/predictions_stacked.csv
            data/out/${{ inputs.RODADA }}/kelly_stakes.csv
            data/out/${{ inputs.RODADA }}/loteca_cartao.txt
            data/out/${{ inputs.RODADA }}/reality_report.*
            data/out/${{ inputs.RODADA }}/debug/**
          if-no-files-found: warn