name: End2End - Odds → Consenso → Predição → Cartão

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  end2end:
    runs-on: ubuntu-latest

    env:
      # Configurações gerais
      SEASON: '2025'
      REGIONS: 'uk,eu,us,au'
      BANKROLL: '1000'
      KELLY_FRACTION: '0.5'
      KELLY_CAP: '0.1'
      ROUND_TO: '1'
      KELLY_TOP_N: '14'
      DEBUG: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Define RODADA_ID e OUT_DIR
        run: |
          set -e
          echo "RODADA_ID=${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo "OUT_DIR=data/out/${GITHUB_RUN_ID}" >> $GITHUB_ENV
          mkdir -p "data/in" "${GITHUB_WORKSPACE}/data/out/${GITHUB_RUN_ID}"

      - name: Sanity - matches_source.csv existe
        run: |
          set -e
          FILE="data/in/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            echo "::error::Arquivo $FILE não encontrado. Crie-o antes de rodar."
            echo "Formato mínimo: match_key,home,away"
            exit 2
          fi
          echo "Entrada OK: $FILE"

      # 1) Coleta de odds (TheOddsAPI)
      - name: Coletar odds (TheOddsAPI)
        env:
          THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
        run: |
          set -e
          if [ -z "${THEODDS_API_KEY}" ]; then
            echo "::warning::THEODDS_API_KEY não configurado — pulando TheOddsAPI."
            exit 0
          fi
          if [ ! -f "scripts/ingest_odds_theoddsapi_safe.py" ]; then
            echo "::error::scripts/ingest_odds_theoddsapi_safe.py não encontrado."
            exit 4
          fi
          python scripts/ingest_odds_theoddsapi_safe.py \
            --rodada "${OUT_DIR}" \
            --regions "${REGIONS}" \
            --debug
          ls -la "${OUT_DIR}" || true

      # 2) Consenso das odds
      - name: Consolidar odds (consensus)
        run: |
          set -e
          python -m scripts.consensus_odds_safe --rodada "${RODADA_ID}"
          echo "==== odds_consensus.csv (preview) ===="
          head -n 20 "data/out/${RODADA_ID}/odds_consensus.csv" || true
          echo "======================================"

      # 3) Predição a partir das odds
      - name: Predizer resultados a partir das odds
        run: |
          set -e
          python scripts/predict_from_odds.py --rodada "${RODADA_ID}" --debug
          echo "==== predictions_market.csv (preview) ===="
          head -n 20 "data/out/${RODADA_ID}/predictions_market.csv" || true
          echo "=========================================="

      # 4) Cartão da Loteca (só depois de tudo acima)
      - name: Gerar cartão da Loteca
        run: |
          set -e
          python scripts/build_cartao.py --rodada "${RODADA_ID}"
          echo "==== loteca_cartao.txt ===="
          cat "data/out/${RODADA_ID}/loteca_cartao.txt" || true

      # 5) Kelly (opcional, não falha o job)
      - name: Publicar Kelly (opcional)
        run: |
          set -e
          if [ -f "scripts/publish_kelly.py" ]; then
            python scripts/publish_kelly.py --rodada "${RODADA_ID}" --debug || true
          else
            echo "::warning::scripts/publish_kelly.py não encontrado — pulando Kelly."
          fi

      # 6) Artefatos de saída
      - name: Upload artefatos
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ env.RODADA_ID }}
          path: |
            data/out/${{ env.RODADA_ID }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/odds_apifootball.csv
            data/out/${{ env.RODADA_ID }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA_ID }}/odds_consensus.csv
            data/out/${{ env.RODADA_ID }}/predictions_market.csv
            data/out/${{ env.RODADA_ID }}/news.csv
            data/out/${{ env.RODADA_ID }}/injuries.csv
            data/out/${{ env.RODADA_ID }}/loteca_cartao.txt
            data/out/${{ env.RODADA_ID }}/kelly_stakes.csv
          if-no-files-found: warn