name: End2End Odds + News + ML

on:
  workflow_dispatch:
    inputs:
      SEASON:
        description: "Ano da temporada"
        required: true
        default: "2025"

jobs:
  end2end:
    runs-on: ubuntu-latest
    env:
      SEASON: ${{ github.event.inputs.SEASON }}
      REGIONS: uk,eu,us,au
      BANKROLL: 1000.0
      KELLY_FRACTION: 0.5
      KELLY_CAP: 0.1
      ROUND_TO: 1.0
      KELLY_TOP_N: 14.0
      DEBUG: true
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      APIFOOT_LEAGUE_IDS: 71,72
      OUT_DIR: data/out/${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check entrada
        run: |
          set -e
          FILE="data/in/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            echo "::error::Arquivo $FILE não encontrado."
            exit 2
          fi
          echo "Entrada OK: $FILE"
          head -n 5 "$FILE" || true

      - name: TheOddsAPI ingest
        run: |
          python scripts/ingest_odds_theoddsapi_safe.py \
            --rodada "${OUT_DIR}" \
            --regions "${REGIONS}" \
            --debug

      - name: API-Football ingest
        run: |
          python -m scripts.ingest_odds_apifootball_rapidapi \
            --rodada "${OUT_DIR}" \
            --season "${SEASON}" \
            --window 2 \
            --fuzzy 0.90 \
            --aliases data/aliases_br.json \
            --debug || true

      - name: Consensus Odds
        run: python -m scripts.consensus_odds_safe --rodada "${OUT_DIR}"

      - name: Market Predictions
        run: python scripts/predict_from_odds.py --rodada "${OUT_DIR}"

      - name: News ingest
        run: python scripts/news_ingest_safe.py || true

      - name: Injuries ingest
        run: python scripts/injuries_apifootball_safe.py || true

      - name: XG Univariado
        run: python scripts/ml_xg_univariado.py --rodada "${OUT_DIR}" --season "${SEASON}" || true

      - name: XG Bivariado
        run: python scripts/ml_xg_bivariado.py --rodada "${OUT_DIR}" --season "${SEASON}" || true

      - name: Calibração Isotônica
        run: python scripts/ml_calibracao_isotonica.py --rodada "${OUT_DIR}" --season "${SEASON}" || true

      - name: Stacking Bivariado
        run: python scripts/ml_stacking_bivariado.py --rodada "${OUT_DIR}" --season "${SEASON}" || true

      - name: Build Cartão
        run: python scripts/build_cartao.py --rodada "${OUT_DIR}"

      - name: Kelly Stakes
        run: python scripts/publish_kelly.py --rodada "${OUT_DIR}"

      - name: Sanity Reality Check
        run: python scripts/sanity_reality_check.py --rodada "${OUT_DIR}" --strict

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ github.run_id }}
          path: data/out/${{ github.run_id }}/*