name: End2End - Odds → Consenso → Predição → Kelly → Cartão

on:
  workflow_dispatch: {}   # executa manualmente, sem inputs

env:
  # Parâmetros do pipeline (ajuste se quiser)
  SEASON: "2025"
  REGIONS: "uk,eu,us,au"
  ODDS_SPORTS: "soccer_brazil_campeonato,soccer_brazil_serie_b,soccer_argentina_primera_division,soccer_argentina_primera_nacional"
  BANKROLL: "1000"
  KELLY_FRACTION: "0.5"
  KELLY_CAP: "0.1"
  ROUND_TO: "1"
  KELLY_TOP_N: "14"

jobs:
  end2end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Preparar diretórios de saída
        id: prep
        shell: bash
        run: |
          set -e
          # ID único desta execução
          echo "RODADA_ID=${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo "OUT_DIR=data/out/${GITHUB_RUN_ID}" >> $GITHUB_ENV
          mkdir -p "data/out/${GITHUB_RUN_ID}"

          # Verifica entrada simples
          FILE_IN="data/in/matches_source.csv"
          if [ ! -f "$FILE_IN" ]; then
            echo "::error::Arquivo $FILE_IN não encontrado. Crie-o com as colunas: home,away"
            exit 2
          fi
          echo "Entrada OK: $FILE_IN"

      - name: Coletar odds (TheOddsAPI)
        env:
          THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
        run: |
          set -e
          python scripts/ingest_odds_theoddsapi_safe.py \
            --rodada "${OUT_DIR}" \
            --regions "${REGIONS}" \
            --sports "${ODDS_SPORTS}" \
            --debug
          ls -la "${OUT_DIR}" || true

      - name: Sincronizar OUT_DIR → data/out/$RODADA_ID
        run: |
          set -e
          rsync -a "${OUT_DIR}/" "data/out/${RODADA_ID}/"
          ls -la "data/out/${RODADA_ID}" || true

      - name: Consolidar odds (consensus)
        run: |
          set -e
          # O módulo de consenso espera SÓ o ID (ele lê data/out/<ID>/...)
          python -m scripts.consensus_odds_safe --rodada "${RODADA_ID}"
          echo "==== odds_consensus.csv (preview) ===="
          head -n 30 "data/out/${RODADA_ID}/odds_consensus.csv" || true
          echo "======================================"

      - name: Predizer resultados a partir das odds de mercado
        run: |
          set -e
          python scripts/predict_from_odds.py --rodada "data/out/${RODADA_ID}" --debug
          echo "==== predictions_market.csv (preview) ===="
          head -n 20 "data/out/${RODADA_ID}/predictions_market.csv" || true

      - name: Publicar Kelly (define picks e coberturas)
        env:
          BANKROLL: ${{ env.BANKROLL }}
          KELLY_FRACTION: ${{ env.KELLY_FRACTION }}
          KELLY_CAP: ${{ env.KELLY_CAP }}
          ROUND_TO: ${{ env.ROUND_TO }}
          KELLY_TOP_N: ${{ env.KELLY_TOP_N }}
        run: |
          set -e
          python scripts/publish_kelly.py --rodada "data/out/${RODADA_ID}" --debug
          echo "==== kelly_stakes.csv (preview) ===="
          head -n 30 "data/out/${RODADA_ID}/kelly_stakes.csv" || true

      - name: Gerar cartão da Loteca (após Kelly)
        run: |
          set -e
          python scripts/build_cartao.py --rodada "data/out/${RODADA_ID}"
          echo "==== loteca_cartao.txt ===="
          cat "data/out/${RODADA_ID}/loteca_cartao.txt" || true

      - name: Upload artefatos
        uses: actions/upload-artifact@v4
        with:
          name: loteca_full_${{ env.RODADA_ID }}
          path: |
            data/out/${{ env.RODADA_ID }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA_ID }}/odds_apifootball.csv
            data/out/${{ env.RODADA_ID }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA_ID }}/odds_consensus.csv
            data/out/${{ env.RODADA_ID }}/predictions_market.csv
            data/out/${{ env.RODADA_ID }}/kelly_stakes.csv
            data/out/${{ env.RODADA_ID }}/loteca_cartao.txt
            data/out/${{ env.RODADA_ID }}/debug/**