name: Lint Workflows

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML syntax
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yamllint
          echo "Validating YAML..."
          yamllint .github/workflows/end2end-odds-news-ml.yml