name: Build Loteca (v4.3RC1+)

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex: 2025-09-20_21)"
        required: true
        default: "2025-09-20_21"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare folders
        run: |
          mkdir -p data/raw data/processed models/artifacts outputs reports

      - name: Export secrets to .env (if any)
        run: |
          echo "BET_API_KEY=${{ secrets.BET_API_KEY }}" >> .env || true
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env || true
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env || true

      - name: Run pipeline
        env:
          LOTECA_RODADA: ${{ github.event.inputs.rodada }}
        run: |
          python scripts/run_pipeline.py --rodada "${LOTECA_RODADA}"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loteca-${{ github.event.inputs.rodada }}
          path: |
            outputs/**
            reports/**
            models/artifacts/**
            models/registry.json
