name: end2end

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Rodada (ex: 2025-09-27_1213)"
        required: true
  push:

jobs:
  end2end:
    runs-on: ubuntu-latest
    env:
      RODADA: ${{ github.event.inputs.rodada || '2025-09-27_1213' }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hotfix merges
        run: python scripts/patch_merge_hotfix.py || true

      - name: Validate input
        run: echo "Entrada OK: data/in/${RODADA}/matches_source.csv"

      - name: W&B login (opcional)
        run: python -m wandb login "${WANDB_API_KEY}" --relogin || true

      # ==== ODDS (sempre reais, fail-fast) ====
      - name: Ingest TheOddsAPI (SAFE)
        run: python scripts/ingest_odds_theoddsapi_safe.py --rodada "$RODADA" --regions "uk,eu,us,au" --debug

      - name: Ingest API-Football RapidAPI (SAFE)
        run: python scripts/ingest_odds_apifootball_rapidapi_safe.py --rodada "$RODADA" --season 2025 --window 14 --fuzzy 0.9 --aliases "data/aliases_br.json" --debug

      - name: Consenso de odds (fail se nenhum provedor)
        run: python scripts/ingest_odds.py --rodada "$RODADA"

      # ==== FEATURES / MODEL ====
      - name: Join features
        run: python scripts/join_features.py --rodada "$RODADA"

      - name: Compute xG
        run: python scripts/compute_xg.py --rodada "$RODADA" --out "data/out/$RODADA/xg.csv"

      - name: Build probabilities
        run: |
          if [ -f "data/out/$RODADA/preds_bivar.csv" ]; then
            echo "Usando preds_bivar..."
          fi
          python scripts/build_probs.py --rodada "$RODADA"

      - name: Blend probabilities
        run: python scripts/blend_probs.py --rodada "$RODADA" --alpha 0.75 || true

      - name: Calibrate probabilities
        run: python scripts/calibrate_probs.py --rodada "$RODADA" || true

      - name: Evaluate risk (robusto)
        run: python scripts/evaluate_risk.py --rodada "$RODADA"

      - name: Loteca picker
        run: python scripts/loteca_picker.py --rodada "$RODADA" --duplos 4 --triplos 2 || true

      - name: News (opcional)
        run: python scripts/ingest_news.py --rodada "$RODADA" --provider auto --lang pt --regions br --days 7 --limit 6 --aliases "data/aliases_br.json" || true

      - name: Scorecard
        run: python scripts/scorecard.py --rodada "$RODADA" --out "data/out/$RODADA/scorecard.html"

      - name: Upload artifact (data/out)
        uses: actions/upload-artifact@v4
        with:
          name: loteca_${{ env.RODADA }}.zip
          path: |
            data/out/${{ env.RODADA }}/**
