name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          echo "pandas
          pyyaml
          requests
          scikit-learn
          wandb
          lxml
          feedparser
          selectolax" > requirements.txt
          pip install -r requirements.txt

      - name: Detect scripts dir
        id: detect
        run: |
          set -e
          for d in pipeline/scripts scripts .; do
            if [ -f "$d/ingest_fixtures_odds.py" ] && \
               [ -f "$d/ingest_standings.py" ] && \
               [ -f "$d/ingest_weather.py" ] && \
               [ -f "$d/ingest_availability.py" ] && \
               [ -f "$d/join_features.py" ]; then
              echo "SCRIPTS_DIR=$d" >> "$GITHUB_ENV"
              echo "Encontrado SCRIPTS_DIR=$d"
              exit 0
            fi
          done
          echo "ERRO: não achei scripts necessários."; exit 2

      - name: Check RAPIDAPI_KEY (safe)
        shell: bash
        run: |
          set -e
          if [ -z "${RAPIDAPI_KEY:-}" ]; then
            echo "ERRO: RAPIDAPI_KEY ausente no ambiente."; exit 2
          fi
          case "$RAPIDAPI_KEY" in
            *$'\n'*|*$'\r'*|*$'\t'*)
              echo "ERRO: RAPIDAPI_KEY contém quebra de linha/tab. Edite o Secret p/ 1 linha."; exit 2;;
          esac
          echo "OK: RAPIDAPI_KEY limpa (len=$(printf %s "$RAPIDAPI_KEY" | wc -c))"

      - name: Ingest fixtures & odds (fixtures)
        run: |
          python "$SCRIPTS_DIR/ingest_fixtures_odds.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest odds (1X2, de-vig, sanity)
        run: |
          python "$SCRIPTS_DIR/ingest_odds.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest standings
        run: |
          python "$SCRIPTS_DIR/ingest_standings.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather
        run: |
          python "$SCRIPTS_DIR/ingest_weather.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest availability (lineups + injuries)
        run: |
          python "$SCRIPTS_DIR/ingest_availability.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        run: |
          python "$SCRIPTS_DIR/join_features.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.LOTECA_RODADA }}
          path: reports/
