name: Loteca End2End

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-09-27_1213)"
        required: true
        type: string
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  end2end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests

      - name: HOTFIX - corrigir merge inseguro no ingest_odds.py
        run: |
          python scripts/patch_merge_hotfix.py || true

      - name: Preparar entrada (se faltar)
        shell: bash
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          mkdir -p "data/in/$RODADA" "data/out/$RODADA"
          FILE="data/in/$RODADA/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            printf 'match_id,home,away,date\n1,Time A,Time B,2025-09-27\n2,Time C,Time D,2025-09-27\n' > "$FILE"
            echo "Criado arquivo de exemplo: $FILE"
          else
            echo "Arquivo já existe: $FILE"
          fi

      # ===== THEODDSAPI =====
      - name: Coletar odds - TheOddsAPI (BR - sports forçados)
        env:
          THEODDSAPI_KEY: ${{ secrets.THEODDSAPI_KEY }}
        shell: bash
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          if [ -z "${THEODDSAPI_KEY}" ]; then
            echo "::warning::Secret THEODDSAPI_KEY não definido. Pulando TheOddsAPI."
            exit 0
          fi
          python scripts/ingest_odds_theoddsapi.py --rodada "$RODADA" \
            --regions "uk,eu,us,au" \
            --sports "soccer_brazil_serie_a,soccer_brazil_serie_b,soccer_brazil_cup" \
            --debug
          if [ -f "data/out/$RODADA/theoddsapi_debug.json" ]; then
            echo "---- theoddsapi_debug.json (primeiros 4000 bytes) ----"
            head -c 4000 "data/out/$RODADA/theoddsapi_debug.json" || true
            echo ""
          fi

      # ===== API-FOOTBALL (RapidAPI) =====
      - name: Coletar odds - API-Football (RapidAPI, BR)
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        shell: bash
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          if [ -z "${RAPIDAPI_KEY}" ]; then
            echo "::warning::Secret RAPIDAPI_KEY não definido. Pulando API-Football."
            exit 0
          fi
          python scripts/ingest_odds_apifootball_rapidapi.py --rodada "$RODADA" --season 2025 --window 14 --fuzzy 0.9 --debug

      # ===== CONSENSO / MERGE FINAL =====
      - name: Ingest Odds (consenso e merge final)
        env:
          THEODDSAPI_KEY: ${{ secrets.THEODDSAPI_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        shell: bash
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          python scripts/ingest_odds.py --rodada "$RODADA"
