name: Build Loteca (v4.3RC1+)

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Ex.: 2025-09-20_21"
        required: true
        default: "2025-09-20_21"
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "utils/**"
      - "data/**"
      - ".github/workflows/loteca_pipeline.yml"
  pull_request:
    branches: [ main ]
