- name: Ingest odds (TheOddsAPI - real)
  run: |
    if [ -z "${ODDS_API_KEY}" ]; then
      echo "::error::ODDS_API_KEY não definido nos Secrets."; exit 2;
    fi

    # 1ª rodada de teste: regiões amplas, matching mais flexível e debug ligado
    python scripts/ingest_odds.py \
      --rodada "${LOTECA_RODADA}" \
      --sport soccer_brazil_campeonato \
      --regions uk,eu,us,au \
      --market h2h \
      --min-match 80 \
      --allow-partial \
      --dump-api \
      --print-map

    test -s "data/out/${LOTECA_RODADA}/odds.csv" || { echo "::error::odds.csv ausente/vazio"; exit 2; }
    head -n 10 "data/out/${LOTECA_RODADA}/odds.csv" || true
