name: Loteca Pipeline (MULTI-LIGAS + CARTÃO)

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-10-05_14)"
        required: true
        default: "2025-10-05_14"

jobs:
  build-loteca:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: ${{ github.event.inputs.rodada }}
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests rapidfuzz==3.9.7 PyYAML==6.0.2

      # 1) Gera matches.csv a partir do seu matches_source.csv
      - name: Ingest matches
        run: |
          python scripts/ingest_matches.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/matches.csv" || { echo "::error::matches.csv ausente/vazio"; exit 2; }

      # 2) ODDS REAIS por liga (ajuste/duplique blocos se usar outras ligas)
      # Brasil (Série A). Mantemos --allow-partial se houver jogos fora da cobertura (ex.: copas).
      - name: Ingest odds Brasil (Série A)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_brazil_campeonato --regions uk,eu --market h2h \
            --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_br.csv" || true

      # Inglaterra (EPL)
      - name: Ingest odds Inglaterra (EPL)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_epl --regions uk,eu --market h2h --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_epl.csv" || true

      # Espanha (La Liga)
      - name: Ingest odds Espanha (La Liga)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_spain_la_liga --regions uk,eu --market h2h \
            --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_esp.csv" || true

      # 3) Merge das odds em um único arquivo (dedup por match_id)
      - name: Merge odds
        run: |
          set -e
          BASE="data/out/${{ env.LOTECA_RODADA }}"
          OUT="${BASE}/odds.csv"
          TMP="${BASE}/odds_tmp.csv"
          : > "${OUT}"
          for f in "${BASE}/odds_br.csv" "${BASE}/odds_epl.csv" "${BASE}/odds_esp.csv"; do
            if [ -s "$f" ]; then
              if [ ! -s "${OUT}" ]; then
                cp "$f" "${OUT}"
              else
                tail -n +2 "$f" >> "${OUT}"
              fi
            fi
          done
          test -s "${OUT}" || { echo "::error::Nenhuma odds coletada"; exit 2; }
          IFS=, read -r HEADER < "${OUT}"
          echo "${HEADER}" > "${TMP}"
          awk -F, 'NR>1 && !seen[$1]++ { print }' "${OUT}" >> "${TMP}"
          mv "${TMP}" "${OUT}"

      # 4) Features
      - name: Build features
        run: |
          python scripts/build_features.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/features.csv" || { echo "::error::features.csv ausente/vazio"; exit 2; }

      # 5) Join final
      - name: Join features
        run: |
          python scripts/join_features.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/joined.csv" || { echo "::error::joined.csv ausente/vazio"; exit 2; }

      # 6) Planejar aposta (até 4 duplos e 2 triplos) -> gera cartao.csv
      - name: Plan bet (cartão Loteca)
        run: |
          python scripts/plan_bet.py --rodada "${{ env.LOTECA_RODADA }}" --max-duplos 4 --max-triplos 2
          test -s "data/out/${{ env.LOTECA_RODADA }}/cartao.csv" || { echo "::error::cartao.csv não gerado"; exit 2; }

      # 7) Publica artefatos finais
      - name: Upload joined
        uses: actions/upload-artifact@v4
        with:
          name: joined-${{ env.LOTECA_RODADA }}
          path: data/out/${{ env.LOTECA_RODADA }}/joined.csv

      - name: Upload cartao
        uses: actions/upload-artifact@v4
        with:
          name: cartao-${{ env.LOTECA_RODADA }}
          path: data/out/${{ env.LOTECA_RODADA }}/cartao.csv
