name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Diagnóstico rápido (mostrar pastas e tentar achar arquivos)
      run: |
        echo "PWD=$(pwd)"
        echo "Pastas até 3 níveis:"
        find . -maxdepth 3 -type d -print | sed 's/^/  - /'
        echo "Procurando ingest_matches_
