name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # >>> ajuste a rodada e o concurso aqui quando precisar <<<
      LOTECA_RODADA: "2025-09-20_21"
      LOTECA_CONCURSO: "1213"

      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          echo "pandas
          numpy
          pyyaml
          requests
          scikit-learn
          wandb
          lxml
          feedparser
          selectolax" > requirements.txt
          pip install -r requirements.txt

      - name: Detect scripts dir (fixo)
        run: |
          if [ -f "pipeline/scripts/ingest_fixtures_odds.py" ]; then
            echo "SCRIPTS_DIR=pipeline/scripts" >> "$GITHUB_ENV"
            echo "Usando SCRIPTS_DIR=pipeline/scripts"
          else
            echo "ERRO: pipeline/scripts não encontrado."; exit 2
          fi

      - name: Check RAPIDAPI_KEY (safe)
        shell: bash
        run: |
          set -e
          if [ -z "${RAPIDAPI_KEY:-}" ]; then
            echo "ERRO: RAPIDAPI_KEY ausente no ambiente."; exit 2
          fi
          case "$RAPIDAPI_KEY" in
            *$'\n'*|*$'\r'*|*$'\t'*)
              echo "ERRO: RAPIDAPI_KEY contém quebra de linha/tab. Edite o Secret p/ 1 linha."; exit 2;;
          esac
          echo "OK: RAPIDAPI_KEY limpa (len=$(printf %s "$RAPIDAPI_KEY" | wc -c))"

      - name: Ingest fixtures & odds (fixtures)
        run: |
          python "$SCRIPTS_DIR/ingest_fixtures_odds.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest odds (1X2, de-vig, sanity)
        run: |
          python "$SCRIPTS_DIR/ingest_odds.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest standings
        run: |
          python "$SCRIPTS_DIR/ingest_standings.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather (Open-Meteo)
        run: |
          python "$SCRIPTS_DIR/ingest_weather.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest availability (lineups + injuries)
        run: |
          python "$SCRIPTS_DIR/ingest_availability.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        run: |
          python "$SCRIPTS_DIR/join_features.py" --rodada "${{ env.LOTECA_RODADA }}"

      # >>> ESTE É O STEP QUE GERA OS PALPITES <<<
      - name: Make Picks (gera 14 secos + duplos)
        run: |
          python "$SCRIPTS_DIR/make_picks.py" \
            --rodada "${{ env.LOTECA_RODADA }}" \
            --duplos 4 \
            --triplos 0 \
            --concurso "${{ env.LOTECA_CONCURSO }}"

      - name: Upload reports (inclui os picks)
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.LOTECA_RODADA }}
          path: |
            reports/
            data/processed/
            data/raw/rodada_${{ env.LOTECA_RODADA }}/
