name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      STANDINGS_API_TOKEN: ${{ secrets.STANDINGS_API_TOKEN }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Detect scripts dir
        id: detect
        run: |
          set -e
          for d in pipeline/scripts scripts .; do
            if [ -f "$d/ingest_standings.py" ] && [ -f "$d/ingest_weather.py" ] && [ -f "$d/ingest_lineups_news.py" ] && [ -f "$d/join_features.py" ]; then
              echo "SCRIPTS_DIR=$d" >> $GITHUB_ENV
              echo "Encontrado SCRIPTS_DIR=$d"
              exit 0
            fi
          done
          echo "ERRO: não achei todos os scripts."; exit 2

          - name: Check RAPIDAPI_KEY (safe)
  shell: bash
  run: |
    python - << 'PY'
import os, sys
t = os.getenv("RAPIDAPI_KEY", "")
if not t:
    print("ERRO: RAPIDAPI_KEY ausente no ambiente."); sys.exit(2)
if any(c in t for c in "\r\n\t"):
    print("ERRO: RAPIDAPI_KEY contém quebra de linha/tab. Edite o Secret para ser 1 linha, sem espaços nem ENTER.")
    sys.exit(2)
print("OK: RAPIDAPI_KEY parece limpa (tamanho:", len(t), ")")
PY


      - name: Ingest fixtures & odds
        run: |
          python "$SCRIPTS_DIR/ingest_fixtures_odds.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest standings
        run: |
          python "$SCRIPTS_DIR/ingest_standings.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather
        run: |
          python "$SCRIPTS_DIR/ingest_weather.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest lineups/news
        run: |
          python "$SCRIPTS_DIR/ingest_lineups_news.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        run: |
          python "$SCRIPTS_DIR/join_features.py" --rodada "${{ env.LOTECA_RODADA }}"
