name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      STANDINGS_API_TOKEN: ${{ secrets.STANDINGS_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Detect scripts dir
        id: detect
        run: |
          set -e
          for d in pipeline/scripts scripts .; do
            if [ -f "$d/ingest_standings.py" ] && [ -f "$d/ingest_weather.py" ] && [ -f "$d/ingest_lineups_news.py" ] && [ -f "$d/join_features.py" ]; then
              echo "SCRIPTS_DIR=$d" >> $GITHUB_ENV
              echo "Encontrado SCRIPTS_DIR=$d"
              exit 0
            fi
          done
          echo "ERRO: não achei todos os scripts."; exit 2

      - name: Ingest standings
        run: python "$SCRIPTS_DIR/ingest_standings.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather
        run: python "$SCRIPTS_DIR/ingest_weather.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest lineups/news
        run: python "$SCRIPTS_DIR/ingest_lineups_news.py" --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        run: python "$SCRIPTS_DIR/join_features.py" --rodada "${{ env.LOTECA_RODADA }}"
