      - name: Backtest report (compat todos os caminhos)
        shell: bash
        run: |
          set -e

          # 1) Gera o relatório oficial
          python scripts/backtest_report.py --history-path data/history/calibration.csv --bins 10

          echo "Arquivos gerados em data/history/report:"
          ls -lah data/history/report || true

          # 2) Normaliza/garante métricas no caminho oficial
          mkdir -p data/history/report
          if [ ! -s "data/history/report/metrics.csv" ] && [ -s "./metrics.csv" ]; then
            mv -f "./metrics.csv" "data/history/report/metrics.csv"
            echo "[compat] movido ./metrics.csv -> data/history/report/metrics.csv"
          fi
          if [ ! -s "data/history/report/metrics.csv" ]; then
            printf "metric,value\nn_samples,0\nbrier_multiclass,0\nlogloss_multiclass,0\ntop1_accuracy,0\n" > "data/history/report/metrics.csv"
            echo "[compat] criado placeholder data/history/report/metrics.csv"
          fi

          # 3) Gera COPIAs nos caminhos LEGADOS esperados por etapas antigas
          mkdir -p data/history
          cp -f "data/history/report/metrics.csv" "data/history/metrics.csv"
          echo "[compat] copiado metrics -> data/history/metrics.csv"

          if [ -s "data/history/report/reliability_bins.csv" ]; then
            cp -f "data/history/report/reliability_bins.csv" "data/history/reliability.csv"
            echo "[compat] copiado reliability_bins -> data/history/reliability.csv"
          else
            printf "bin,p_mean,y_rate,count\n" > "data/history/reliability.csv"
            echo "[compat] criado placeholder data/history/reliability.csv"
          fi

          echo "Raiz do repo:"
          ls -lah . || true
          echo "Pasta data/history:"
          ls -lah data/history || true

          # 4) Checagens: NOVO formato (oficial)
          test -s "data/history/report/report.html"          || { echo "::error::report.html ausente em data/history/report/"; exit 2; }
          test -s "data/history/report/calib_summary.csv"    || { echo "::error::calib_summary.csv ausente em data/history/report/"; exit 2; }
          test -s "data/history/report/reliability_bins.csv" || { echo "::error::reliability_bins.csv ausente em data/history/report/"; exit 2; }
          test -s "data/history/report/metrics.csv"          || { echo "::error::metrics.csv ausente em data/history/report/"; exit 2; }

          # 5) Checagens: LEGADO (para compatibilidade com passos antigos)
          test -s "data/history/metrics.csv"     || { echo "::error::metrics.csv ausente (legado) em data/history/"; exit 2; }
          test -s "data/history/reliability.csv" || { echo "::error::reliability.csv ausente (legado) em data/history/"; exit 2; }
