name: Build Loteca (v4.3RC1+)

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Rodada no formato AAAA-MM-DD_NN (ex.: 2025-09-20_21)"
        required: true
        default: "2025-09-20_21"
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "utils/**"
      - "data/**"
      - ".github/workflows/loteca_pipeline.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Mostrar árvore do repo (debug)
        run: |
          echo "== pwd ==" && pwd
          echo "== ls -la ==" && ls -la
          echo "== ls scripts ==" && ls -la scripts || true
          echo "== ls utils ==" && ls -la utils || true
          echo "== ls data ==" && ls -la data || true

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # Dependências básicas caso não tenha requirements.txt
          pip install pandas pyyaml requests python-dateutil

      # IMPORTANTE: garante que "from utils.io import ..." funcione
      - name: Definir PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Validar estrutura mínima (matches/odds)
        run: |
          python - << 'PY'
          import os, sys
          ok = True
          for p in ["scripts/run_pipeline.py",
                    "scripts/ingest_odds.py",
                    "scripts/ingest_matches.py",
                    "scripts/scorecard.py",
                    "utils/__init__.py",
                    "utils/io.py",
                    "data/raw/matches.csv",
                    "data/raw/odds.csv"]:
              if not os.path.exists(p):
                  print(f"[ERRO] Arquivo não encontrado: {p}")
                  ok = False
          if not ok:
              sys.exit(2)
          print("✔ Estrutura OK")
          PY

      - name: Rodar pipeline Loteca
        env:
          LOTECA_RODADA: ${{ inputs.rodada }}
        run: |
          set -e
          echo "=== RUNNING: python scripts/run_pipeline.py --rodada \"${LOTECA_RODADA}\" ==="
          python scripts/run_pipeline.py --rodada "${LOTECA_RODADA}"

      - name: Publicar artefatos (cartão/relatórios)
        uses: actions/upload-artifact@v4
        with:
          name: loteca_outputs_${{ inputs.rodada }}
          path: |
            outputs/**
            reports/**
          if-no-files-found: warn
