name: Loteca Pipeline

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-09-27_1213)"
        required: true
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: HOTFIX — corrigir merge inseguro no ingest_odds.py
        run: |
          python scripts/patch_merge_hotfix.py
          echo '>>> Verificação do merge em scripts/ingest_odds.py'
          nl -ba scripts/engest_odds.py 2>/dev/null || true
          nl -ba scripts/ingest_odds.py | sed -n '1,220p' | grep -n 'merge(.*on=\["home_n","away_n"\].*how="left")' || true

      - name: Prepare sample input if missing
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          mkdir -p "data/in/$RODADA" "data/out/$RODADA"
          FILE="data/in/$RODADA/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            printf 'match_id,home,away,date\n1,Time A,Time B,2025-09-27\n2,Time C,Time D,2025-09-27\n' > "$FILE"
            echo "Criado arquivo de exemplo: $FILE"
          else
            echo "Arquivo já existe: $FILE"
          fi

      - name: Run ingest_odds_apifootball (placeholder resiliente)
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          python scripts/ingest_odds_apifootball_rapidapi.py --rodada "$RODADA"

      - name: Run ingest_odds (final merge & consenso)
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          python scripts/ingest_odds.py --rodada "$RODADA"
