name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      STANDINGS_API_TOKEN: ${{ secrets.STANDINGS_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Diagnóstico rápido de caminhos
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          echo "Pastas (até 3 níveis):"
          find . -maxdepth 3 -type d -print | sed 's/^/  - /'
          echo "Procurando scripts essenciais:"
          find . -maxdepth 6 -type f -name "ingest_*.py" -print | sed 's/^/  - /'

      - name: Ingest standings (CSV por padrão)
        shell: bash
        run: |
          python pipeline/scripts/ingest_standings.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather (Open-Meteo)
        shell: bash
        run: |
          python pipeline/scripts/ingest_weather.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest lineups/news
        shell: bash
        run: |
          python pipeline/scripts/ingest_lineups_news.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        shell: bash
        run: |
          python pipeline/scripts/join_features.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.LOTECA_RODADA }}
          path: reports/
