name: Loteca Pipeline (PRO) – Odds+RapidAPI+W&B+Optimizer

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-10-05_14)"
        required: true
        type: string
        default: "2025-10-05_14"

jobs:
  build-loteca:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: ${{ github.event.inputs.rodada }}
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_PROJECT: loteca-framework
      WANDB_ENTITY: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests rapidfuzz==3.9.7 PyYAML==6.0.2 wandb

      # W&B start
      - name: Weights & Biases - start run
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python - << 'PY'
          import os, wandb
          key=os.environ.get("WANDB_API_KEY","")
          if key:
            wandb.login(key=key)
          PY
          python scripts/wandb_hook.py start --rodada "${{ env.LOTECA_RODADA }}" --project "${{ env.WANDB_PROJECT }}" --entity "${{ env.WANDB_ENTITY }}"

      # 1) Matches
      - name: Ingest matches
        run: |
          python scripts/ingest_matches.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/matches.csv" || { echo "::error::matches.csv ausente/vazio"; exit 2; }

      # 2) Odds – TheOddsAPI
      - name: Ingest odds Brasil (Série A)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_brazil_campeonato --regions uk,eu --market h2h \
            --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_br.csv" || true

      - name: Ingest odds Inglaterra (EPL)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_epl --regions uk,eu --market h2h --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_epl.csv" || true

      - name: Ingest odds Espanha (La Liga)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/ingest_odds.py --rodada "${{ env.LOTECA_RODADA }}" \
            --sport soccer_spain_la_liga --regions uk,eu --market h2h \
            --min-match 88 --allow-partial
          mv "data/out/${{ env.LOTECA_RODADA }}/odds.csv" "data/out/${{ env.LOTECA_RODADA }}/odds_esp.csv" || true

      # 3) Odds – RapidAPI (API-Football)
      - name: Ingest odds (RapidAPI - API-Football)
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          if [ -n "${RAPIDAPI_KEY}" ]; then
            python scripts/ingest_odds_apifootball_rapidapi.py \
              --rodada "${{ env.LOTECA_RODADA }}" \
              --allow-partial \
              --country-hint "Brazil" \
              --days-window 2 \
              --min-match 85
          else
            echo "RAPIDAPI_KEY não definido; pulando passo API-Football."
          fi

      # 4) Merge odds
      - name: Merge odds
        run: |
          set -e
          BASE="data/out/${{ env.LOTECA_RODADA }}"
          OUT="${BASE}/odds.csv"
          TMP="${BASE}/odds_tmp.csv"
          : > "${OUT}"
          for f in "${BASE}/odds_br.csv" "${BASE}/odds_epl.csv" "${BASE}/odds_esp.csv" "${BASE}/odds_apifootball.csv"; do
            if [ -s "$f" ]; then
              if [ ! -s "${OUT}" ]; then
                cp "$f" "${OUT}"
              else
                tail -n +2 "$f" >> "${OUT}"
              fi
            fi
          done
          test -s "${OUT}" || { echo "::error::Nenhuma odds coletada"; exit 2; }
          IFS=, read -r HEADER < "${OUT}"
          echo "${HEADER}" > "${TMP}"
          awk -F, 'NR>1 && !seen[$1]++ { print }' "${OUT}" >> "${TMP}"
          mv "${TMP}" "${OUT}"

      # 5) Features
      - name: Build features
        run: |
          python scripts/build_features.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/features.csv" || { echo "::error::features.csv ausente/vazio"; exit 2; }

      # 6) Join
      - name: Join features
        run: |
          python scripts/join_features.py --rodada "${{ env.LOTECA_RODADA }}"
          test -s "data/out/${{ env.LOTECA_RODADA }}/joined.csv" || { echo "::error::joined.csv ausente/vazio"; exit 2; }

      # 7) Cartão (OPTIMIZER: 4 duplos, 2 triplos)
      - name: Plan bet (optimizer)
        run: |
          python scripts/plan_bet_opt.py --rodada "${{ env.LOTECA_RODADA }}" --max-duplos 4 --max-triplos 2
          test -s "data/out/${{ env.LOTECA_RODADA }}/cartao.csv" || { echo "::error::cartao.csv não gerado"; exit 2; }

      # W&B log
      - name: Weights & Biases - log artifacts
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python - << 'PY'
          import os, wandb
          key=os.environ.get("WANDB_API_KEY","")
          if key:
            wandb.login(key=key)
          PY
          python scripts/wandb_hook.py log --rodada "${{ env.LOTECA_RODADA }}" --project "${{ env.WANDB_PROJECT }}" --entity "${{ env.WANDB_ENTITY }}"

      # 8) Artefatos
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: loteca-${{ env.LOTECA_RODADA }}
          path: |
            data/out/${{ env.LOTECA_RODADA }}/joined.csv
            data/out/${{ env.LOTECA_RODADA }}/cartao.csv
            data/out/${{ env.LOTECA_RODADA }}/odds.csv
