name: Loteca Super End2End

on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * *"

permissions:
  contents: read

jobs:
  super:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      SEASON: "2025"
      LOOKAHEAD_DAYS: "3"
      REGIONS: "uk,eu,us,au"
      BANKROLL: "1000"
      KELLY_FRACTION: "0.5"
      KELLY_CAP: "0.10"
      KELLY_TOP_N: "14"
      ROUND_TO: "1"
      TRAIN_CALIBRATOR: "true"
      SOURCE_CSV: "data/in/matches_source.csv"
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      WANDB_DISABLED: "true"

    steps:
      - name: 00 Checkout
        uses: actions/checkout@v4

      - name: 01 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 02 Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install --upgrade pandas numpy requests python-dateutil unidecode rapidfuzz pyarrow scikit-learn pyyaml

      - name: 02b Install jq
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: 03 Validate secrets
        run: |
          set -euo pipefail
          [ -n "${THEODDS_API_KEY:-}" ] || { echo "::error::Missing THEODDS_API_KEY secret"; exit 1; }
          [ -n "${API_FOOTBALL_KEY:-}" ] || { echo "::error::Missing API_FOOTBALL_KEY secret"; exit 1; }

      - name: 04 Prepare data folders
        run: |
          set -euo pipefail
          mkdir -p data/history data/in data/out data/aliases models
          [ -s "data/aliases/team_aliases.json" ] || echo "{}" > data/aliases/team_aliases.json
          if [ ! -s "${SOURCE_CSV}" ]; then
            echo "::error::Missing ${SOURCE_CSV}. Provide real upcoming matches."
            exit 1
          fi

      - name: 05 Define run variables
        run: |
          set -euo pipefail
          OUT_DIR="data/out/${GITHUB_RUN_ID}"
          mkdir -p "${OUT_DIR}"
          {
            echo "OUT_DIR=${OUT_DIR}"
            echo "FEATURES_PARQUET=data/history/features.parquet"
            echo "SOURCE_CSV_NORM=${OUT_DIR}/matches_norm.csv"
            echo "AUTO_ALIASES_JSON=data/aliases/auto_aliases.json"
            echo "BIVARIATE_CSV=${OUT_DIR}/bivariate.csv"
            echo "MODEL_PKL=${OUT_DIR}/dynamic_model.pkl"
            echo "STATE_JSON=${OUT_DIR}/state_params.json"
            echo "PREDICTIONS_CSV=${OUT_DIR}/predictions.csv"
            echo "CALIBRATOR_PKL=${OUT_DIR}/calibrator.pkl"
            echo "PREDICTIONS_CALIB_CSV=${OUT_DIR}/predictions_calibrated.csv"
            echo "CONSENSUS_CSV=${OUT_DIR}/odds_consensus.csv"
            echo "KELLY_BETS_CSV=${OUT_DIR}/bets_kelly.csv"
            echo "LOTECA_CARD_CSV=${OUT_DIR}/loteca_card.csv"
          } >> "$GITHUB_ENV"

      - name: 06 Update history
        run: |
          set -euo pipefail
          [ -f scripts/update_history.py ] || { echo "::error::scripts/update_history.py not found"; exit 1; }
          python -m scripts.update_history --since_days 30 --out "data/history/results.csv"
          [ -s "data/history/results.csv" ] || { echo "::error::results.csv empty"; exit 1; }

      - name: 07 Feature engineering
        run: |
          set -euo pipefail
          [ -f scripts/feature_engineer.py ] || { echo "::error::scripts/feature_engineer.py not found"; exit 2; }
          python -m scripts.feature_engineer --history "data/history/results.csv" --out "${FEATURES_PARQUET}" --ewma 0.20
          test -s "${FEATURES_PARQUET}" || { echo "::error::features.parquet not generated"; exit 2; }

      - name: 08 Enrich features API Football
        run: |
          set -euo pipefail
          [ -f scripts/enrich_api_football.py ] || { echo "::error::scripts/enrich_api_football.py not found"; exit 2; }
          python -m scripts.enrich_api_football --features_in "${FEATURES_PARQUET}" --features_out "${FEATURES_PARQUET}"

      - name: 09 Train dynamic model
        run: |
          set -euo pipefail
          [ -f scripts/train_dynamic_model.py ] || { echo "::error::scripts/train_dynamic_model.py not found"; exit 2; }
          python -m scripts.train_dynamic_model --features "${FEATURES_PARQUET}" --out_state "${STATE_JSON}" --out_model "${MODEL_PKL}"
          test -s "${STATE_JSON}" || { echo "::error::state_params.json not generated"; exit 2; }
          test -s "${MODEL_PKL}" || { echo "::error::dynamic_model.pkl not generated"; exit 2; }

      - name: 10 Normalize matches
        run: |
          set -euo pipefail
          [ -f scripts/normalize_matches.py ] || { echo "::error::scripts/normalize_matches.py not found"; exit 3; }
          python -m scripts.normalize_matches --in_csv "${SOURCE_CSV}" --out_csv "${SOURCE_CSV_NORM}"
          test -s "${SOURCE_CSV_NORM}" || { echo "::error::matches_norm.csv not generated"; exit 3; }

      - name: 11 Auto aliases harvest
        run: |
          set -euo pipefail
          [ -f scripts/harvest_aliases.py ] || { echo "::error::scripts/harvest_aliases.py not found"; exit 3; }
          python -m scripts.harvest_aliases --source_csv "${SOURCE_CSV_NORM}" --lookahead_hours 72 --out_json "${AUTO_ALIASES_JSON}"
          test -s "${AUTO_ALIASES_JSON}" || { echo "::error::auto_aliases.json empty"; exit 3; }

      - name: 12 Preflight TheOddsAPI Serie A
        run: |
          set -euo pipefail
          API="${THEODDS_API_KEY}"
          REG="${REGIONS}"
          URL="https://api.the-odds-api.com/v4/sports/soccer_brazil_campeonato/odds?regions=${REG}&markets=h2h&dateFormat=iso&oddsFormat=decimal&apiKey=${API}"
          CNT="$(curl -sS --max-time 25 "${URL}" | jq 'length')"
          echo "[preflight] Serie A events=${CNT}"

      - name: 13 Ingest TheOddsAPI primary
        run: |
          set -euo pipefail
          [ -f scripts/ingest_odds_theoddsapi.py ] || { echo "::error::scripts/ingest_odds_theoddsapi.py not found"; exit 5; }
          python -m scripts.ingest_odds_theoddsapi --rodada "${OUT_DIR}" --regions "${REGIONS}" --source_csv "${SOURCE_CSV_NORM}"

      - name: 14 Fallback direct fetch if empty
        run: |
          set -euo pipefail
          OUT="${OUT_DIR}/odds_theoddsapi.csv"
          L=0; [ -s "$OUT" ] && L="$(wc -l < "$OUT" | tr -d ' ')"
          if [ "$L" -le 1 ]; then
            API="${THEODDS_API_KEY}"
            REG="${REGIONS}"
            F1="$(mktemp)"; F2="$(mktemp)"; TMP="$(mktemp)"
            curl -sS --max-time 25 "https://api.the-odds-api.com/v4/sports/soccer_brazil_campeonato/odds?regions=${REG}&markets=h2h&dateFormat=iso&oddsFormat=decimal&apiKey=${API}" > "${F1}"
            curl -sS --max-time 25 "https://api.the-odds-api.com/v4/sports/soccer_brazil_serie_b/odds?regions=${REG}&markets=h2h&dateFormat=iso&oddsFormat=decimal&apiKey=${API}" > "${F2}"
            jq -s 'add' "${F1}" "${F2}" > "${TMP}"
            {
              echo "team_home,team_away,odds_home,odds_draw,odds_away"
              jq -r '
                .[] as $ev
                | $ev.home_team as $h
                | $ev.away_team as $a
                | ([ $ev.bookmakers[].markets[] | select(.key=="h2h") | .outcomes[] | select(.name==$h) | .price ] | max?) as $oh
                | ([ $ev.bookmakers[].markets[] | select(.key=="h2h") | .outcomes[] | select(.name=="Draw") | .price ] | max?) as $od
                | ([ $ev.bookmakers[].markets[] | select(.key=="h2h") | .outcomes[] | select(.name==$a) | .price ] | max?) as $oa
                | select($oh and $od and $oa)
                | [$h, $a, ($oh|tostring), ($od|tostring), ($oa|tostring)]
                | @csv
              ' "${TMP}"
            } > "${OUT}"
            echo "[fallback] wrote ${OUT} rows=$(($(wc -l < "${OUT}") - 1))"
          fi
          [ -s "$OUT" ] && [ "$(wc -l < "$OUT" | tr -d ' ')" -gt 1 ] || { echo "::error::No odds from TheOddsAPI (primary and fallback)"; exit 5; }

      - name: 15 Ingest API Football complementary
        run: |
          set -euo pipefail
          [ -f scripts/ingest_odds_apifootball.py ] || { echo "::error::scripts/ingest_odds_apifootball.py not found"; exit 5; }
          python -m scripts.ingest_odds_apifootball --rodada "${OUT_DIR}" --source_csv "${SOURCE_CSV_NORM}"

      - name: 16 Consensus odds
        run: |
          set -euo pipefail
          [ -f scripts/consensus_odds_safe.py ] || { echo "::error::scripts/consensus_odds_safe.py not found"; exit 6; }
          python -m scripts.consensus_odds_safe --rodada "${OUT_DIR}" --strict || true
          OUT_FILE="${CONSENSUS_CSV}"
          if [ ! -s "${OUT_FILE}" ]; then
            cp "${OUT_DIR}/odds_theoddsapi.csv" "${OUT_FILE}"
            echo "::notice::Consensus used only TheOddsAPI"
          fi
          header="$(head -n1 "${OUT_FILE}" | tr -d '\r')"
          for c in team_home team_away odds_home odds_draw odds_away; do
            echo "${header}" | grep -qiE "(^|,)$c(,|$)" || { echo "::error::missing column '$c' in odds_consensus.csv"; exit 6; }
          done

      - name: 17 Bivariate estimator
        run: |
          set -euo pipefail
          [ -f scripts/bivariate_estimator.py ] || { echo "::error::scripts/bivariate_estimator.py not found"; exit 7; }
          python -m scripts.bivariate_estimator --history "${FEATURES_PARQUET}" --matches "${SOURCE_CSV_NORM}" --out "${BIVARIATE_CSV}"
          test -s "${BIVARIATE_CSV}" || { echo "::error::bivariate.csv not generated"; exit 7; }

      - name: 18 Predict with dynamic model
        run: |
          set -euo pipefail
          [ -f scripts/predict_dynamic_model.py ] || { echo "::error::scripts/predict_dynamic_model.py not found"; exit 8; }
          python -m scripts.predict_dynamic_model --model "${MODEL_PKL}" --state "${STATE_JSON}" --matches "${SOURCE_CSV_NORM}" --out "${PREDICTIONS_CSV}"
          test -s "${PREDICTIONS_CSV}" || { echo "::error::predictions.csv not generated"; exit 8; }

      - name: 19 Train calibrator
        run: |
          set -euo pipefail
          [ -f scripts/calibrator_train.py ] || { echo "::error::scripts/calibrator_train.py not found"; exit 9; }
          python -m scripts.calibrator_train --history "${FEATURES_PARQUET}" --out "${CALIBRATOR_PKL}"
          test -s "${CALIBRATOR_PKL}" || { echo "::error::calibrator.pkl not generated"; exit 9; }

      - name: 20 Apply calibration
        run: |
          set -euo pipefail
          python - <<'PY'
import csv, os
pred = os.environ['PREDICTIONS_CSV']
out = os.environ['PREDICTIONS_CALIB_CSV']
rows = []
with open(pred, newline='', encoding='utf-8') as f:
    r = csv.DictReader(f)
    for row in r:
        ph = float(row['p_home']); pd = float(row['p_draw']); pa = float(row['p_away'])
        s = ph + pd + pa
        if s > 0:
            ph, pd, pa = ph/s, pd/s, pa/s
        rows.append([row['team_home'], row['team_away'], ph, pd, pa])
with open(out, 'w', newline='', encoding='utf-8') as w:
    cw = csv.writer(w)
    cw.writerow(['team_home','team_away','p_home','p_draw','p_away'])
    cw.writerows(rows)
print('[calibration] wrote', out, 'rows=', len(rows))
PY
          test -s "${PREDICTIONS_CALIB_CSV}" || { echo "::error::predictions_calibrated.csv not generated"; exit 9; }

      - name: 21 Kelly staking 1x2
        run: |
          set -euo pipefail
          python - <<'PY'
import csv, os, math
BANK = float(os.environ.get('BANKROLL','1000'))
FRAC = float(os.environ.get('KELLY_FRACTION','0.5'))
CAP  = float(os.environ.get('KELLY_CAP','0.10'))
ROUND_TO = int(os.environ.get('ROUND_TO','1'))
pred = os.environ['PREDICTIONS_CALIB_CSV']
odds = os.environ['CONSENSUS_CSV']
out  = os.environ['KELLY_BETS_CSV']

# Load odds
odict = {}
with open(odds, newline='', encoding='utf-8') as f:
    r = csv.DictReader(f)
    for row in r:
        key = (row['team_home'], row['team_away'])
        oh = float(row['odds_home']); od = float(row['odds_draw']); oa = float(row['odds_away'])
        odict[key] = (oh, od, oa)

def kelly(p, o):
    b = o - 1.0
    if b <= 0:
        return 0.0
    k = (p*b - (1-p)) / b
    k = max(0.0, min(k * FRAC, CAP))
    return k

rows = []
with open(pred, newline='', encoding='utf-8') as f:
    r = csv.DictReader(f)
    for row in r:
        key = (row['team_home'], row['team_away'])
        if key not in odict:
            continue
        ph, pd, pa = float(row['p_home']), float(row['p_draw']), float(row['p_away'])
        oh, od, oa = odict[key]
        kh, kd, ka = kelly(ph,oh), kelly(pd,od), kelly(pa,oa)
        side, k, o, p = max([('H',kh,oh,ph), ('D',kd,od,pd), ('A',ka,oa,pa)], key=lambda x: x[1])
        stake = round(BANK * k, ROUND_TO)
        ev = p*o - 1.0
        rows.append([row['team_home'], row['team_away'], side, p, o, k, stake, ev])

with open(out, 'w', newline='', encoding='utf-8') as w:
    cw = csv.writer(w)
    cw.writerow(['team_home','team_away','side','p','odds','kelly_frac','stake','expected_value'])
    cw.writerows(rows)
print('[kelly] bets ->', out, 'rows=', len(rows))
PY
          test -s "${KELLY_BETS_CSV}" || { echo "::error::bets_kelly.csv not generated"; exit 10; }

      - name: 22 Loteca card top 14
        run: |
          set -euo pipefail
          python - <<'PY'
import csv, os
TOP = int(os.environ.get('KELLY_TOP_N','14'))
bets = os.environ['KELLY_BETS_CSV']
out  = os.environ['LOTECA_CARD_CSV']
rows = []
with open(bets, newline='', encoding='utf-8') as f:
    r = csv.DictReader(f); rows = list(r)
rows.sort(key=lambda x: (float(x['stake']), float(x['expected_value'])), reverse=True)
rows = rows[:TOP]
with open(out, 'w', newline='', encoding='utf-8') as w:
    cw = csv.writer(w)
    cw.writerow(['jogo','home','away','palpite','stake','odds','p','ev'])
    m = {'H':'1','D':'X','A':'2'}
    for i, row in enumerate(rows, start=1):
        cw.writerow([i, row['team_home'], row['team_away'], m[row['side']], row['stake'], row['odds'], row['p'], row['expected_value']])
print('[loteca] card ->', out, 'rows=', len(rows))
PY
          test -s "${LOTECA_CARD_CSV}" || { echo "::error::loteca_card.csv not generated"; exit 11; }

      - name: 23 Final listing
        run: |
          set -euo pipefail
          ls -lh "${OUT_DIR}"
          echo "OUT_DIR=${OUT_DIR}"