name: Loteca End2End

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Pasta/rodada (ex: 2025-09-27_1213)"
        required: true
        default: "2025-09-27_1213"
      season:
        description: "Temporada (ex: 2025)"
        required: true
        default: "2025"
      regions:
        description: "Regiões TheOddsAPI"
        required: true
        default: "uk,eu,us,au"
      debug:
        description: "Debug verbose"
        required: true
        default: "true"

env:
  RODADA: ${{ github.event.inputs.rodada }}
  SEASON: ${{ github.event.inputs.season }}
  REGIONS: ${{ github.event.inputs.regions }}
  DEBUG: ${{ github.event.inputs.debug }}

jobs:
  end2end:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      THEODDS_API_KEY: ${{ secrets.THEODDS_API_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hotfix merge guard
        run: python scripts/patch_merge_hotfix.py || true

      - name: Checar entrada
        run: |
          set -e
          if [ ! -f "data/in/${RODADA}/matches_source.csv" ]; then
            echo "ERRO: data/in/${RODADA}/matches_source.csv não encontrado"
            exit 2
          fi
          echo "Entrada OK: data/in/${RODADA}/matches_source.csv"

      - name: Checar segredos
        run: |
          set -e
          if [ -z "${THEODDS_API_KEY}" ]; then echo "FALTANDO THEODDS_API_KEY"; exit 3; else echo "THEODDS_API_KEY: OK"; fi
          if [ -z "${RAPIDAPI_KEY}" ]; then echo "FALTANDO RAPIDAPI_KEY"; exit 3; else echo "RAPIDAPI_KEY: OK"; fi

      - name: W&B login
        run: |
          python -m wandb login "${WANDB_API_KEY}" --relogin || true
          echo "[wandb] login executado"

      - name: Sanity - wrappers SAFE existem
        run: |
          set -e
          grep -n "consensus-safe" scripts/consensus_odds_safe.py || (echo "CONSENSUS_SAFE_NOT_FOUND"; exit 4)
          grep -n "theoddsapi-safe" scripts/ingest_odds_theoddsapi_safe.py || (echo "SAFE_NOT_FOUND"; exit 4)
          python -c "import importlib.util,sys; ok=bool(importlib.util.find_spec('scripts.consensus_odds_safe')); print('[check] consensus_safe exists:', ok); sys.exit(0 if ok else 5)"

      - name: Ingest TheOddsAPI (SAFE)
        env:
          REGIONS: ${{ env.REGIONS }}
          DEBUG: ${{ env.DEBUG }}
        run: |
          set -e
          if [ -n "${THEODDS_API_KEY}" ]; then
            EXTRA=""
            if [ "${DEBUG}" = "true" ]; then EXTRA="--debug"; fi
            python scripts/ingest_odds_theoddsapi_safe.py \
              --rodada "${RODADA}" \
              --regions "${REGIONS}" \
              ${EXTRA}
          else
            echo "[theoddsapi-safe] SKIP: THEODDS_API_KEY ausente."
          fi

      - name: Ingest API-Football RapidAPI (SAFE)
        env:
          DEBUG: ${{ env.DEBUG }}
        run: |
          set -e
          if [ -n "${RAPIDAPI_KEY}" ]; then
            EXTRA=""
            if [ "${DEBUG}" = "true" ]; then EXTRA="--debug"; fi
            if [ -f "scripts/ingest_odds_apifootball_rapidapi_safe.py" ]; then
              python scripts/ingest_odds_apifootball_rapidapi_safe.py \
                --rodada "${RODADA}" \
                --season "${SEASON}" \
                ${EXTRA} || true
            else
              python -m scripts.ingest_odds_apifootball_rapidapi \
                --rodada "${RODADA}" \
                --season "${SEASON}" \
                --window 2 \
                --fuzzy 0.90 \
                --aliases data/aliases_br.json \
                ${EXTRA} || true
            fi
          else
            echo "[apifootball-safe] SKIP: RAPIDAPI_KEY ausente."
          fi

      - name: Consensus (SAFE)
        run: |
          set -e
          python -m scripts.consensus_odds_safe --rodada "${RODADA}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: odds_${{ env.RODADA }}
          path: |
            data/out/${{ env.RODADA }}/odds_theoddsapi.csv
            data/out/${{ env.RODADA }}/unmatched_theoddsapi.csv
            data/out/${{ env.RODADA }}/odds_apifootball.csv
            data/out/${{ env.RODADA }}/unmatched_apifootball.csv
            data/out/${{ env.RODADA }}/odds_consensus.csv
            data/out/${{ env.RODADA }}/debug/**
          if-no-files-found: warn
