name: Loteca Pipeline

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-09-27_1213)"
        required: true
  push:
    branches: [ "main" ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Show ingest_odds merge line (sanity check)
        run: |
          echo ">>> Expect: merged = matches.merge(cons, on=[\"home_n\",\"away_n\"], how=\"left\")"
          nl -ba scripts/ingest_odds.py | sed -n '1,180p' | grep -n 'merge(cons, on=\["home_n", "away_n"\], how="left")' || true
          echo "----- file head -----"
          head -n 30 scripts/ingest_odds.py
          echo "----- file tail -----"
          tail -n 30 scripts/ingest_odds.py

      - name: Prepare sample input (if missing)
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          mkdir -p "data/in/$RODADA" "data/out/$RODADA"
          if [ ! -f "data/in/$RODADA/matches_source.csv" ]; then
            cat > "data/in/$RODADA/matches_source.csv" <<'CSV'
match_id,home,away,date
1,Time A,Time B,2025-09-27
2,Time C,Time D,2025-09-27
CSV
          fi

      - name: Run ingest_odds_apifootball (placeholder resiliente)
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          python scripts/ingest_odds_apifootball_rapidapi.py --rodada "$RODADA"

      - name: Run ingest_odds (final merge & consenso)
        run: |
          RODADA="${{ github.event.inputs.rodada || '2025-09-27_1213' }}"
          python scripts/ingest_odds.py --rodada "$RODADA"
