name: Loteca Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOTECA_RODADA: "2025-09-20_21"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export secrets to env
        run: echo "secrets available"
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          STANDINGS_API_TOKEN: ${{ secrets.STANDINGS_API_TOKEN }}

      - name: Ingest standings
        run: python pipeline/scripts/ingest_standings.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest weather (Open-Meteo)
        run: python pipeline/scripts/ingest_weather.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Ingest lineups/news
        run: python pipeline/scripts/ingest_lineups_news.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Join & context score
        run: python pipeline/scripts/join_features.py --rodada "${{ env.LOTECA_RODADA }}"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.LOTECA_RODADA }}
          path: reports/
