name: Loteca End2End

on:
  workflow_dispatch:
    inputs:
      rodada:
        description: "Identificador da rodada (ex.: 2025-09-27_1213)"
        required: false
        type: string
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  end2end:
    runs-on: ubuntu-latest

    env:
      RODADA: ${{ github.event.inputs.rodada != '' && github.event.inputs.rodada || '2025-09-27_1213' }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
      THEODDSAPI_KEY: ${{ secrets.THEODDSAPI_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      PYTHONWARNINGS: ignore

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hotfix merge inseguro
        shell: bash
        run: |
          python scripts/patch_merge_hotfix.py || true

      - name: Preparar entrada
        shell: bash
        run: |
          mkdir -p "data/in/$RODADA" "data/out/$RODADA" "artifacts/$RODADA" "data"
          # aliases BR (caso o repo ainda não tenha)
          if [ ! -f data/aliases_br.json ]; then
            cat > data/aliases_br.json << 'JSON'
{
  "atletico mineiro": ["atlético mg", "atlético-mg", "atletico mg", "clube atletico mineiro", "atlético mineiro", "atletico-mg"],
  "mirassol": ["mirassol fc", "mirassol futebol clube"],
  "palmeiras": ["se palmeiras", "sociedade esportiva palmeiras", "palestra italia"],
  "corinthians": ["sc corinthians paulista", "sport club corinthians paulista", "corinthians paulista"],
  "sao paulo": ["são paulo", "são paulo fc", "sao paulo fc"],
  "santos": ["santos fc"],
  "flamengo": ["cr flamengo", "clube de regatas do flamengo"],
  "fluminense": ["fluminense fc"],
  "botafogo": ["botafogo fr", "botafogo rj"],
  "vasco da gama": ["vasco", "cr vasco da gama"],
  "gremio": ["grêmio", "gremio fbpa", "grêmio fbpa"],
  "internacional": ["sc internacional", "sport club internacional"],
  "bahia": ["bahia ec", "ec bahia", "esporte clube bahia"],
  "fortaleza": ["fortaleza ec", "esporte clube fortaleza"],
  "ceara": ["ceará", "ceara sc"],
  "america mg": ["américa mg", "america mineiro", "america futebol clube", "américa futebol clube"],
  "cruzeiro": ["cruzeiro ec", "esporte clube cruzeiro"],
  "cuiaba": ["cuiabá", "cuiaba ec"],
  "bragantino": ["red bull bragantino", "rb bragantino"],
  "athletico pr": ["athletico paranaense", "atletico pr", "atlético pr"],
  "goias": ["goiás", "goias ec"],
  "avai": ["avaí", "avai fc"],
  "chapecoense": ["chapecoense af", "a chapecoense"],
  "ponte preta": ["aa ponte preta"],
  "juventude": ["ec juventude"],
  "crb": ["clube de regatas brasil"],
  "vitoria": ["esporte clube vitoria", "vitória"],
  "sport recife": ["sport club do recife", "sport"],
  "nautico": ["náutico", "clube nautico capibaribe"],
  "sampaio correa": ["sampaio corrêa", "sampaio correia"],
  "botafogo sp": ["botafogo ribeirão preto", "botafogo rp"],
  "ituano": ["ituano fc"]
}
JSON
          fi

          FILE="data/in/$RODADA/matches_source.csv"
          if [ ! -f "$FILE" ]; then
            printf 'match_id,home,away,date\n1,Atletico Mineiro,Mirassol,2025-09-27\n2,Time C,Time D,2025-09-27\n' > "$FILE"
            echo "Criado: $FILE"
          else
            echo "Entrada OK: $FILE"
          fi

      # ===================== W&B (opcional) =====================
      - name: Weights and Biases login
        if: ${{ env.WANDB_API_KEY != '' }}
        shell: bash
        run: |
          python -m wandb login "${WANDB_API_KEY}" --relogin || true
          echo "[wandb] login executado"

      # ===================== ODDS =====================
      - name: Coletar odds TheOddsAPI (auto)
        if: ${{ env.THEODDSAPI_KEY != '' }}
        shell: bash
        run: |
          python scripts/ingest_odds_theoddsapi.py --rodada "$RODADA" --regions "uk,eu,us,au" --debug || true
          if [ -f "data/out/$RODADA/theoddsapi_debug.json" ]; then
            echo "---- theoddsapi_debug.json (head) ----"
            head -c 4000 "data/out/$RODADA/theoddsapi_debug.json" || true
            echo ""
          fi

      - name: Coletar odds API-Football (RapidAPI BR)
        if: ${{ env.RAPIDAPI_KEY != '' }}
        shell: bash
        run: |
          python scripts/ingest_odds_apifootball_rapidapi.py --rodada "$RODADA" --season 2025 --window 14 --fuzzy 0.9 --aliases "data/aliases_br.json" --debug

      - name: Consolidar odds (consenso)
        shell: bash
        run: |
          python scripts/ingest_odds.py --rodada "$RODADA"

      # ===================== FEATURE ENGINEERING / xG =====================
      - name: Gerar features base
        shell: bash
        run: |
          python scripts/join_features.py --rodada "$RODADA"

      - name: Calcular xG
        shell: bash
        run: |
          python scripts/compute_xg.py --rodada "$RODADA" --out "data/out/$RODADA/xg.csv"

      # ===================== (opcionais de modelagem) =====================
      - name: Build probabilities
        shell: bash
        run: |
          python scripts/build_probabilities.py --rodada "$RODADA" \
            --in "data/out/$RODADA/preds_bivar.csv" \
            --odds "data/out/$RODADA/odds.csv" \
            --out "data/out/$RODADA/probabilities.csv" || \
          python scripts/build_probabilities.py --rodada "$RODADA" \
            --odds "data/out/$RODADA/odds.csv" \
            --out "data/out/$RODADA/probabilities.csv"

      - name: Evaluate risk e edge
        shell: bash
        run: |
          python scripts/evaluate_risk.py --rodada "$RODADA" \
            --probs "data/out/$RODADA/probabilities.csv" \
            --odds "data/out/$RODADA/odds.csv" \
            --out "data/out/$RODADA/risk_report.csv"

      - name: Scorecard relatório
        shell: bash
        run: |
          python scripts/scorecard.py --rodada "$RODADA" --out "data/out/$RODADA/scorecard.html"

      # ===================== EXPORT/ARTIFACTS =====================
      - name: Exportar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: loteca_${{ env.RODADA }}
          path: |
            data/out/${{ env.RODADA }}/**
            artifacts/${{ env.RODADA }}/**
            data/aliases_br.json
